/* Generated by WalkLang. C is the primary backend and is intended to stay inspectable. */

#include "walk_runtime.h"
/* Build generated C with runtime/walk_runtime.c and the host platform file. */

WalkInt pick(WalkBool flag);

WalkInt pick(WalkBool flag) {
    /* source: explicit_systems_defer.walk:4:5 */
    WalkString ____defer_io_write_line_1_1 = "outer";
    /* source: explicit_systems_defer.walk:5:5 */
    if (flag) {
        /* source: explicit_systems_defer.walk:6:9 */
        WalkString ____defer_io_write_line_1_2 = "inner";
        /* source: explicit_systems_defer.walk:7:9 */
        walk_rt_io_write_line(____defer_io_write_line_1_2);
        walk_rt_io_write_line(____defer_io_write_line_1_1);
        return 9;
        walk_rt_io_write_line(____defer_io_write_line_1_2);
    }
    /* source: explicit_systems_defer.walk:8:5 */
    walk_rt_io_write_line(____defer_io_write_line_1_1);
    return 4;
    walk_rt_io_write_line(____defer_io_write_line_1_1);
}

int main(int argc, char **argv) {
    walk_rt_init(argc, argv);
    /* source: explicit_systems_defer.walk:10:1 */
    walk_rt_print_int((WalkInt)(pick(true)));
    return 0;
}
