/* Generated by WalkLang. C is the primary backend and is intended to stay inspectable. */

#include "walk_runtime.h"
/* Build generated C with runtime/walk_runtime.c and the host platform file. */

WalkInt add(WalkInt a, WalkInt b);
WalkInt fact(WalkInt n);

WalkInt add(WalkInt a, WalkInt b) {
    /* source: functions.walk:2:5 */
    return (a + b);
}

WalkInt fact(WalkInt n) {
    /* source: functions.walk:5:5 */
    if ((n <= 1)) {
        /* source: functions.walk:6:9 */
        return 1;
    }
    /* source: functions.walk:7:5 */
    return (n * fact((n - 1)));
}

int main(int argc, char **argv) {
    walk_rt_init(argc, argv);
    /* source: functions.walk:9:1 */
    walk_rt_print_int((WalkInt)(add(2, 3)));
    /* source: functions.walk:10:1 */
    walk_rt_print_int((WalkInt)(fact(5)));
    return 0;
}
