/* Generated by WalkLang. C is the primary backend and is intended to stay inspectable. */

#include "walk_runtime.h"
/* Build generated C with runtime/walk_runtime.c and the host platform file. */

int main(int argc, char **argv) {
    walk_rt_init(argc, argv);
    /* source: hello.walk:1:1 */
    walk_rt_print_string((WalkString)("hello"));
    /* source: hello.walk:2:1 */
    walk_rt_print_int((WalkInt)((1 + 2)));
    /* source: hello.walk:3:1 */
    walk_rt_print_bool((WalkBool)(true));
    return 0;
}
