package emitter

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"walklang/internal/ast"
	"walklang/internal/builtins"
	"walklang/internal/diagnostic"
)

func EmitC(program *ast.Program) (string, error) {
	return EmitCWithModules(program, nil)
}

func EmitTestC(program *ast.Program) (string, error) {
	return EmitTestCWithModules(program, nil)
}

func EmitCWithModules(program *ast.Program, modules map[string]*ast.Program) (string, error) {
	e := newCEmitter(modules)
	return e.emit(program, false)
}

func EmitTestCWithModules(program *ast.Program, modules map[string]*ast.Program) (string, error) {
	e := newCEmitter(modules)
	return e.emit(program, true)
}

type cEmitter struct {
	tempID              int
	indent              int
	currentModule       string
	modules             map[string]*ast.Program
	moduleFunctionNames map[string]map[string]bool
	structs             map[string]*ast.StructDecl
	structOrder         []string
	deferScopes         []deferScope
	loopCleanupMarks    []int
}

type deferScope struct {
	cleanups []string
}

func newCEmitter(modules map[string]*ast.Program) *cEmitter {
	if modules == nil {
		modules = map[string]*ast.Program{}
	}
	structs := map[string]*ast.StructDecl{}
	for name, decl := range collectStructDecls(modules) {
		structs[name] = decl
	}
	return &cEmitter{
		modules:             modules,
		moduleFunctionNames: collectModuleFunctionNames(modules),
		structs:             structs,
	}
}

func (e *cEmitter) emit(program *ast.Program, testsOnly bool) (string, error) {
	e.addProgramStructs(program)
	e.structOrder = e.sortedStructNames()
	var out strings.Builder
	out.WriteString("/* Generated by WalkLang. C is the primary backend and is intended to stay inspectable. */\n\n")
	out.WriteString("#include \"walk_runtime.h\"\n")
	out.WriteString("/* Build generated C with runtime/walk_runtime.c and the host platform file. */\n\n")
	for _, name := range e.structOrder {
		rendered, err := e.emitStructDecl(e.structs[name])
		if err != nil {
			return "", err
		}
		out.WriteString(rendered)
		out.WriteString(fmt.Sprintf("typedef struct { %s *items; WalkSize len; } %s;\n\n", cStructName(name), cStructArrayName(name)))
	}
	for _, name := range sortedModuleNames(e.modules) {
		e.currentModule = name
		for _, statement := range e.modules[name].Statements {
			fn, ok := statement.(*ast.FuncDecl)
			if !ok || len(fn.TypeParams) > 0 {
				continue
			}
			prototype, err := e.emitFunctionSignature(fn, true)
			if err != nil {
				return "", err
			}
			out.WriteString(prototype)
			out.WriteString(";\n")
		}
	}
	e.currentModule = ""
	for _, statement := range program.Statements {
		fn, ok := statement.(*ast.FuncDecl)
		if !ok || len(fn.TypeParams) > 0 {
			continue
		}
		prototype, err := e.emitFunctionSignature(fn, true)
		if err != nil {
			return "", err
		}
		out.WriteString(prototype)
		out.WriteString(";\n")
	}
	genericInstances, err := e.collectGenericInstances(program)
	if err != nil {
		return "", err
	}
	for _, instance := range genericInstances {
		prototype, err := e.emitGenericInstanceSignature(instance)
		if err != nil {
			return "", err
		}
		out.WriteString(prototype)
		out.WriteString(";\n")
	}
	if hasFunctions(program) || hasModuleFunctions(e.modules) || len(genericInstances) > 0 {
		out.WriteString("\n")
	}
	for _, name := range sortedModuleNames(e.modules) {
		e.currentModule = name
		for _, statement := range e.modules[name].Statements {
			fn, ok := statement.(*ast.FuncDecl)
			if !ok || len(fn.TypeParams) > 0 {
				continue
			}
			rendered, err := e.emitFunction(fn)
			if err != nil {
				return "", err
			}
			out.WriteString(rendered)
			out.WriteString("\n")
		}
	}
	e.currentModule = ""
	for _, statement := range program.Statements {
		fn, ok := statement.(*ast.FuncDecl)
		if !ok || len(fn.TypeParams) > 0 {
			continue
		}
		rendered, err := e.emitFunction(fn)
		if err != nil {
			return "", err
		}
		out.WriteString(rendered)
		out.WriteString("\n")
	}
	for _, instance := range genericInstances {
		rendered, err := e.emitGenericInstance(instance)
		if err != nil {
			return "", err
		}
		out.WriteString(rendered)
		out.WriteString("\n")
	}

	out.WriteString("int main(int argc, char **argv) {\n")
	e.indent = 1
	out.WriteString("    walk_rt_init(argc, argv);\n")
	if testsOnly {
		out.WriteString("    long long walk_tests = 0;\n")
		out.WriteString("    long long walk_failures = 0;\n")
	}
	mainScope := e.pushDeferScope()
	for _, statement := range program.Statements {
		switch s := statement.(type) {
		case *ast.FuncDecl, *ast.StructDecl, *ast.Import, *ast.Export:
			continue
		case *ast.TestDecl:
			if !testsOnly {
				continue
			}
			lines, err := e.emitTestDecl(s)
			if err != nil {
				return "", err
			}
			lines = prependSourceComment(s.Location, lines)
			for _, line := range lines {
				out.WriteString(e.indentString())
				out.WriteString(line)
				out.WriteByte('\n')
			}
			continue
		case *ast.Assert:
			if !testsOnly {
				continue
			}
		}
		if testsOnly {
			if _, ok := statement.(*ast.TestDecl); !ok {
				switch statement.(type) {
				case *ast.VarDecl, *ast.Assignment:
				default:
					continue
				}
			}
		}
		lines, err := e.emitStatementWithComment(statement)
		if err != nil {
			return "", err
		}
		for _, line := range lines {
			out.WriteString(e.indentString())
			out.WriteString(line)
			out.WriteByte('\n')
		}
	}
	for _, line := range e.deferredCleanupLines(mainScope) {
		out.WriteString(e.indentString())
		out.WriteString(line)
		out.WriteByte('\n')
	}
	e.popDeferScope()
	if testsOnly {
		out.WriteString("    if (walk_failures == 0) {\n")
		out.WriteString("        printf(\"ok %lld tests\\n\", walk_tests);\n")
		out.WriteString("    } else {\n")
		out.WriteString("        printf(\"failed %lld of %lld tests\\n\", walk_failures, walk_tests);\n")
		out.WriteString("    }\n")
		out.WriteString("    return walk_failures == 0 ? 0 : 1;\n")
	} else {
		out.WriteString("    return 0;\n")
	}
	out.WriteString("}\n")
	return out.String(), nil
}

func hasFunctions(program *ast.Program) bool {
	for _, statement := range program.Statements {
		if fn, ok := statement.(*ast.FuncDecl); ok && len(fn.TypeParams) == 0 {
			return true
		}
	}
	return false
}

func hasModuleFunctions(modules map[string]*ast.Program) bool {
	for _, program := range modules {
		if hasFunctions(program) {
			return true
		}
	}
	return false
}

func sortedModuleNames(modules map[string]*ast.Program) []string {
	names := make([]string, 0, len(modules))
	for name := range modules {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func collectModuleFunctionNames(modules map[string]*ast.Program) map[string]map[string]bool {
	result := map[string]map[string]bool{}
	for module, program := range modules {
		result[module] = map[string]bool{}
		for _, statement := range program.Statements {
			if fn, ok := statement.(*ast.FuncDecl); ok && fn.Receiver == "" && len(fn.TypeParams) == 0 {
				result[module][fn.Name] = true
			}
		}
	}
	return result
}

func collectStructDecls(modules map[string]*ast.Program) map[string]*ast.StructDecl {
	result := map[string]*ast.StructDecl{}
	for _, name := range sortedModuleNames(modules) {
		for _, statement := range modules[name].Statements {
			if decl, ok := statement.(*ast.StructDecl); ok {
				result[decl.Name] = decl
			}
		}
	}
	return result
}

func collectBuiltinStructDecls() map[string]*ast.StructDecl {
	result := map[string]*ast.StructDecl{}
	for _, decl := range builtins.StructDecls() {
		result[decl.Name] = decl
	}
	return result
}

func (e *cEmitter) addProgramStructs(program *ast.Program) {
	for _, statement := range program.Statements {
		if decl, ok := statement.(*ast.StructDecl); ok {
			e.structs[decl.Name] = decl
		}
	}
}

func (e *cEmitter) sortedStructNames() []string {
	names := make([]string, 0, len(e.structs))
	seen := map[string]bool{}
	visiting := map[string]bool{}
	var visit func(string)
	visit = func(name string) {
		if seen[name] || visiting[name] {
			return
		}
		visiting[name] = true
		if decl := e.structs[name]; decl != nil {
			deps := make([]string, 0)
			for _, field := range decl.Fields {
				deps = append(deps, structDependencies(field.Type)...)
			}
			sort.Strings(deps)
			for _, dep := range deps {
				if _, ok := e.structs[dep]; ok && dep != name {
					visit(dep)
				}
			}
		}
		visiting[name] = false
		seen[name] = true
		names = append(names, name)
	}
	all := make([]string, 0, len(e.structs))
	for name := range e.structs {
		all = append(all, name)
	}
	sort.Strings(all)
	for _, name := range all {
		visit(name)
	}
	return names
}

func structDependencies(typeName ast.Type) []string {
	switch typeName.Kind {
	case ast.TypeStruct:
		return []string{typeName.Name}
	case ast.TypeArray:
		if typeName.Elem == nil {
			return nil
		}
		return structDependencies(*typeName.Elem)
	case ast.TypeFunction:
		var deps []string
		for _, param := range typeName.Params {
			deps = append(deps, structDependencies(param)...)
		}
		if typeName.Return != nil {
			deps = append(deps, structDependencies(*typeName.Return)...)
		}
		return deps
	default:
		return nil
	}
}

type genericDecl struct {
	module string
	fn     *ast.FuncDecl
}

type genericInstance struct {
	callee   string
	module   string
	fn       *ast.FuncDecl
	typeArgs []ast.Type
	cName    string
}

func (e *cEmitter) collectGenericInstances(program *ast.Program) ([]genericInstance, error) {
	decls := e.collectGenericDecls(program)
	instances := map[string]genericInstance{}
	var queue []genericInstance
	addCall := func(call *ast.Call, module string) error {
		if len(call.TypeArgs) == 0 || containsGenericType(call.TypeArgs) {
			return nil
		}
		callee := call.Callee
		if module != "" && !strings.Contains(callee, ".") {
			if _, ok := decls[module+"."+callee]; ok {
				callee = module + "." + callee
			}
		}
		decl, ok := decls[callee]
		if !ok {
			return errorAt(call.Loc(), "internal error: generic function %s is not defined", callee)
		}
		key := genericInstanceKey(callee, call.TypeArgs)
		if _, ok := instances[key]; ok {
			return nil
		}
		instance := genericInstance{
			callee:   callee,
			module:   decl.module,
			fn:       decl.fn,
			typeArgs: call.TypeArgs,
			cName:    genericInstanceName(callee, call.TypeArgs),
		}
		instances[key] = instance
		queue = append(queue, instance)
		return nil
	}
	for _, name := range sortedModuleNames(e.modules) {
		calls := collectGenericCalls(e.modules[name].Statements, true)
		for _, call := range calls {
			if err := addCall(call, name); err != nil {
				return nil, err
			}
		}
	}
	for _, call := range collectGenericCalls(program.Statements, true) {
		if err := addCall(call, ""); err != nil {
			return nil, err
		}
	}
	for i := 0; i < len(queue); i++ {
		instance := queue[i]
		clone := instantiateGeneric(instance)
		for _, call := range collectGenericCalls(clone.Body, false) {
			if err := addCall(call, instance.module); err != nil {
				return nil, err
			}
		}
	}
	result := make([]genericInstance, 0, len(instances))
	for _, instance := range instances {
		result = append(result, instance)
	}
	sort.Slice(result, func(i, j int) bool {
		return result[i].cName < result[j].cName
	})
	return result, nil
}

func (e *cEmitter) collectGenericDecls(program *ast.Program) map[string]genericDecl {
	decls := map[string]genericDecl{}
	for _, name := range sortedModuleNames(e.modules) {
		for _, statement := range e.modules[name].Statements {
			fn, ok := statement.(*ast.FuncDecl)
			if ok && len(fn.TypeParams) > 0 {
				decls[name+"."+fn.Name] = genericDecl{module: name, fn: fn}
			}
		}
	}
	for _, statement := range program.Statements {
		fn, ok := statement.(*ast.FuncDecl)
		if ok && len(fn.TypeParams) > 0 {
			decls[fn.Name] = genericDecl{fn: fn}
		}
	}
	return decls
}

func collectGenericCalls(statements []ast.Statement, skipGenericFunctions bool) []*ast.Call {
	var calls []*ast.Call
	var visitStatement func(ast.Statement)
	var visitExpression func(ast.Expression)
	visitStatement = func(statement ast.Statement) {
		switch s := statement.(type) {
		case *ast.FuncDecl:
			if skipGenericFunctions && len(s.TypeParams) > 0 {
				return
			}
			for _, nested := range s.Body {
				visitStatement(nested)
			}
		case *ast.VarDecl:
			visitExpression(s.Value)
		case *ast.Assignment:
			visitExpression(s.Target)
			visitExpression(s.Value)
		case *ast.Out:
			visitExpression(s.Value)
		case *ast.Do:
			visitExpression(s.Value)
		case *ast.Defer:
			if s.Value != nil {
				visitExpression(s.Value)
			}
		case *ast.TestDecl:
			for _, nested := range s.Body {
				visitStatement(nested)
			}
		case *ast.Assert:
			visitExpression(s.Value)
		case *ast.Return:
			visitExpression(s.Value)
		case *ast.If:
			visitExpression(s.Cond)
			for _, nested := range s.Then {
				visitStatement(nested)
			}
			for _, nested := range s.Else {
				visitStatement(nested)
			}
		case *ast.While:
			visitExpression(s.Cond)
			for _, nested := range s.Body {
				visitStatement(nested)
			}
		case *ast.Repeat:
			visitExpression(s.Count)
			for _, nested := range s.Body {
				visitStatement(nested)
			}
		case *ast.For:
			visitExpression(s.Iterable)
			for _, nested := range s.Body {
				visitStatement(nested)
			}
		}
	}
	visitExpression = func(expression ast.Expression) {
		switch e := expression.(type) {
		case *ast.Prefix:
			for _, arg := range e.Args {
				visitExpression(arg)
			}
		case *ast.Call:
			if len(e.TypeArgs) > 0 {
				calls = append(calls, e)
			}
			if e.Receiver != nil {
				visitExpression(e.Receiver)
			}
			for _, arg := range e.Args {
				visitExpression(arg)
			}
		case *ast.Input:
			if e.Prompt != nil {
				visitExpression(e.Prompt)
			}
		case *ast.ArrayLiteral:
			for _, element := range e.Elements {
				visitExpression(element)
			}
		case *ast.Index:
			visitExpression(e.Target)
			visitExpression(e.Index)
		case *ast.FieldAccess:
			visitExpression(e.Target)
		}
	}
	for _, statement := range statements {
		visitStatement(statement)
	}
	return calls
}

func (e *cEmitter) emitGenericInstanceSignature(instance genericInstance) (string, error) {
	clone := instantiateGeneric(instance)
	return e.emitFunctionSignature(clone, true)
}

func (e *cEmitter) emitGenericInstance(instance genericInstance) (string, error) {
	clone := instantiateGeneric(instance)
	previousModule := e.currentModule
	e.currentModule = instance.module
	rendered, err := e.emitFunction(clone)
	e.currentModule = previousModule
	return rendered, err
}

func instantiateGeneric(instance genericInstance) *ast.FuncDecl {
	bindings := map[string]ast.Type{}
	for i, param := range instance.fn.TypeParams {
		bindings[param] = instance.typeArgs[i]
	}
	return cloneFuncDecl(instance.fn, bindings, instance.cName)
}

func cloneFuncDecl(fn *ast.FuncDecl, bindings map[string]ast.Type, cName string) *ast.FuncDecl {
	params := make([]ast.Param, 0, len(fn.Params))
	for _, param := range fn.Params {
		params = append(params, ast.Param{Name: param.Name, Type: substituteType(param.Type, bindings)})
	}
	body := cloneStatements(fn.Body, bindings)
	return &ast.FuncDecl{
		Location:   fn.Location,
		Name:       fn.Name,
		Receiver:   fn.Receiver,
		Params:     params,
		ReturnType: substituteType(fn.ReturnType, bindings),
		Body:       body,
		CName:      cName,
	}
}

func cloneStatements(statements []ast.Statement, bindings map[string]ast.Type) []ast.Statement {
	result := make([]ast.Statement, 0, len(statements))
	for _, statement := range statements {
		result = append(result, cloneStatement(statement, bindings))
	}
	return result
}

func cloneStatement(statement ast.Statement, bindings map[string]ast.Type) ast.Statement {
	switch s := statement.(type) {
	case *ast.VarDecl:
		return &ast.VarDecl{Location: s.Location, Name: s.Name, Annotation: substituteType(s.Annotation, bindings), Value: cloneExpression(s.Value, bindings), Mutable: s.Mutable}
	case *ast.Assignment:
		return &ast.Assignment{Location: s.Location, Target: cloneExpression(s.Target, bindings), Value: cloneExpression(s.Value, bindings)}
	case *ast.Out:
		return &ast.Out{Location: s.Location, Value: cloneExpression(s.Value, bindings)}
	case *ast.Do:
		return &ast.Do{Location: s.Location, Value: cloneExpression(s.Value, bindings)}
	case *ast.Defer:
		var value ast.Expression
		if s.Value != nil {
			value = cloneExpression(s.Value, bindings)
		}
		return &ast.Defer{Location: s.Location, Value: value}
	case *ast.TestDecl:
		return &ast.TestDecl{Location: s.Location, Name: s.Name, Body: cloneStatements(s.Body, bindings)}
	case *ast.Assert:
		return &ast.Assert{Location: s.Location, Value: cloneExpression(s.Value, bindings)}
	case *ast.Import:
		return &ast.Import{Location: s.Location, Module: s.Module}
	case *ast.Export:
		return &ast.Export{Location: s.Location, Name: s.Name}
	case *ast.FuncDecl:
		return cloneFuncDecl(s, bindings, s.CName)
	case *ast.StructDecl:
		fields := make([]ast.StructField, 0, len(s.Fields))
		for _, field := range s.Fields {
			fields = append(fields, ast.StructField{Location: field.Location, Name: field.Name, Type: substituteType(field.Type, bindings)})
		}
		return &ast.StructDecl{Location: s.Location, Name: s.Name, Fields: fields}
	case *ast.Return:
		return &ast.Return{Location: s.Location, Value: cloneExpression(s.Value, bindings)}
	case *ast.If:
		return &ast.If{Location: s.Location, Cond: cloneExpression(s.Cond, bindings), Then: cloneStatements(s.Then, bindings), Else: cloneStatements(s.Else, bindings)}
	case *ast.While:
		return &ast.While{Location: s.Location, Cond: cloneExpression(s.Cond, bindings), Body: cloneStatements(s.Body, bindings)}
	case *ast.Repeat:
		return &ast.Repeat{Location: s.Location, Count: cloneExpression(s.Count, bindings), Body: cloneStatements(s.Body, bindings)}
	case *ast.For:
		return &ast.For{Location: s.Location, Name: s.Name, Iterable: cloneExpression(s.Iterable, bindings), Body: cloneStatements(s.Body, bindings)}
	case *ast.Break:
		return &ast.Break{Location: s.Location}
	case *ast.Continue:
		return &ast.Continue{Location: s.Location}
	default:
		return statement
	}
}

func cloneExpression(expression ast.Expression, bindings map[string]ast.Type) ast.Expression {
	base := cloneExprBase(expression, bindings)
	switch e := expression.(type) {
	case *ast.Literal:
		return &ast.Literal{ExprBase: base, Kind: e.Kind, Value: e.Value}
	case *ast.InterpolatedString:
		parts := make([]ast.InterpolatedStringPart, 0, len(e.Parts))
		for _, part := range e.Parts {
			var expression ast.Expression
			if part.Expression != nil {
				expression = cloneExpression(part.Expression, bindings)
			}
			parts = append(parts, ast.InterpolatedStringPart{Literal: part.Literal, Expression: expression})
		}
		return &ast.InterpolatedString{ExprBase: base, Parts: parts}
	case *ast.Name:
		return &ast.Name{ExprBase: base, Identifier: e.Identifier}
	case *ast.Prefix:
		args := make([]ast.Expression, 0, len(e.Args))
		for _, arg := range e.Args {
			args = append(args, cloneExpression(arg, bindings))
		}
		return &ast.Prefix{ExprBase: base, Operator: e.Operator, Args: args}
	case *ast.Call:
		args := make([]ast.Expression, 0, len(e.Args))
		for _, arg := range e.Args {
			args = append(args, cloneExpression(arg, bindings))
		}
		typeArgs := make([]ast.Type, 0, len(e.TypeArgs))
		for _, typeArg := range e.TypeArgs {
			typeArgs = append(typeArgs, substituteType(typeArg, bindings))
		}
		var receiver ast.Expression
		if e.Receiver != nil {
			receiver = cloneExpression(e.Receiver, bindings)
		}
		return &ast.Call{ExprBase: base, Callee: e.Callee, Receiver: receiver, Method: e.Method, Args: args, TypeArgs: typeArgs}
	case *ast.Input:
		var prompt ast.Expression
		if e.Prompt != nil {
			prompt = cloneExpression(e.Prompt, bindings)
		}
		return &ast.Input{ExprBase: base, Prompt: prompt}
	case *ast.ArrayLiteral:
		elements := make([]ast.Expression, 0, len(e.Elements))
		for _, element := range e.Elements {
			elements = append(elements, cloneExpression(element, bindings))
		}
		return &ast.ArrayLiteral{ExprBase: base, Elements: elements}
	case *ast.Index:
		return &ast.Index{ExprBase: base, Target: cloneExpression(e.Target, bindings), Index: cloneExpression(e.Index, bindings)}
	case *ast.FieldAccess:
		return &ast.FieldAccess{ExprBase: base, Target: cloneExpression(e.Target, bindings), Field: e.Field}
	default:
		return expression
	}
}

func cloneExprBase(expression ast.Expression, bindings map[string]ast.Type) ast.ExprBase {
	return ast.ExprBase{Location: expression.Loc(), Type: substituteType(expression.ExprType(), bindings)}
}

func substituteType(typeName ast.Type, bindings map[string]ast.Type) ast.Type {
	switch typeName.Kind {
	case ast.TypeGeneric:
		if replacement, ok := bindings[typeName.Name]; ok {
			if typeName.Nullable {
				replacement.Nullable = true
			}
			return replacement
		}
		return typeName
	case ast.TypeArray:
		if typeName.Elem == nil {
			return typeName
		}
		elem := substituteType(*typeName.Elem, bindings)
		result := ast.ArrayOf(elem)
		result.Nullable = typeName.Nullable
		return result
	case ast.TypeFunction:
		params := make([]ast.Type, 0, len(typeName.Params))
		for _, param := range typeName.Params {
			params = append(params, substituteType(param, bindings))
		}
		if typeName.Return == nil {
			return typeName
		}
		ret := substituteType(*typeName.Return, bindings)
		result := ast.FuncType(params, ret)
		result.Nullable = typeName.Nullable
		return result
	default:
		return typeName
	}
}

func containsGenericType(types []ast.Type) bool {
	for _, typeName := range types {
		if typeContainsGeneric(typeName) {
			return true
		}
	}
	return false
}

func typeContainsGeneric(typeName ast.Type) bool {
	switch typeName.Kind {
	case ast.TypeGeneric:
		return true
	case ast.TypeArray:
		return typeName.Elem != nil && typeContainsGeneric(*typeName.Elem)
	case ast.TypeFunction:
		for _, param := range typeName.Params {
			if typeContainsGeneric(param) {
				return true
			}
		}
		return typeName.Return != nil && typeContainsGeneric(*typeName.Return)
	default:
		return false
	}
}

func genericInstanceKey(callee string, typeArgs []ast.Type) string {
	parts := make([]string, 0, len(typeArgs)+1)
	parts = append(parts, callee)
	for _, typeArg := range typeArgs {
		parts = append(parts, typeSignature(typeArg))
	}
	return strings.Join(parts, "|")
}

func genericInstanceName(callee string, typeArgs []ast.Type) string {
	parts := make([]string, 0, len(typeArgs)+1)
	parts = append(parts, strings.ReplaceAll(callee, ".", "__"))
	for _, typeArg := range typeArgs {
		parts = append(parts, typeSignature(typeArg))
	}
	return strings.Join(parts, "__")
}

func typeSignature(typeName ast.Type) string {
	var out string
	switch typeName.Kind {
	case ast.TypeArray:
		if typeName.Elem == nil {
			out = "array_unknown"
		} else {
			out = "array_" + typeSignature(*typeName.Elem)
		}
	case ast.TypeFunction:
		parts := make([]string, 0, len(typeName.Params)+1)
		for _, param := range typeName.Params {
			parts = append(parts, typeSignature(param))
		}
		ret := "void"
		if typeName.Return != nil {
			ret = typeSignature(*typeName.Return)
		}
		out = "func_" + strings.Join(parts, "_") + "_to_" + ret
	case ast.TypeStruct, ast.TypeGeneric:
		out = typeName.Name
	default:
		out = string(typeName.Kind)
	}
	out = strings.ReplaceAll(out, "?", "_nullable")
	if typeName.Nullable {
		out += "_nullable"
	}
	return out
}

func (e *cEmitter) emitStructDecl(decl *ast.StructDecl) (string, error) {
	var out strings.Builder
	out.WriteString("typedef struct {\n")
	for _, field := range decl.Fields {
		fieldType, err := cValueType(field.Type)
		if err != nil {
			return "", err
		}
		out.WriteString(fmt.Sprintf("    %s %s;\n", fieldType, field.Name))
	}
	out.WriteString(fmt.Sprintf("} %s;\n", cStructName(decl.Name)))
	return out.String(), nil
}

func (e *cEmitter) emitFunction(fn *ast.FuncDecl) (string, error) {
	signature, err := e.emitFunctionSignature(fn, false)
	if err != nil {
		return "", err
	}
	var out strings.Builder
	out.WriteString(signature)
	out.WriteString(" {\n")
	e.indent = 1
	lines, err := e.emitBlock(fn.Body)
	if err != nil {
		return "", err
	}
	for _, line := range lines {
		out.WriteString(e.indentString())
		out.WriteString(line)
		out.WriteByte('\n')
	}
	if fn.ReturnType.Kind == ast.TypeVoid {
		out.WriteString("    return;\n")
	}
	out.WriteString("}\n")
	return out.String(), nil
}

func (e *cEmitter) emitFunctionSignature(fn *ast.FuncDecl, prototype bool) (string, error) {
	ret, err := cReturnType(fn.ReturnType)
	if err != nil {
		return "", err
	}
	params := make([]string, 0, len(fn.Params))
	for _, param := range fn.Params {
		rendered, err := cDecl(param.Type, param.Name, true)
		if err != nil {
			return "", err
		}
		params = append(params, rendered)
	}
	if len(params) == 0 {
		params = append(params, "void")
	}
	return fmt.Sprintf("%s %s(%s)", ret, e.cFunctionDeclName(fn), strings.Join(params, ", ")), nil
}

func (e *cEmitter) emitBlock(statements []ast.Statement) ([]string, error) {
	return e.emitBlockWithOptions(statements, false)
}

func (e *cEmitter) emitLoopBlock(statements []ast.Statement) ([]string, error) {
	return e.emitBlockWithOptions(statements, true)
}

func (e *cEmitter) emitBlockWithOptions(statements []ast.Statement, loopBody bool) ([]string, error) {
	scopeIndex := e.pushDeferScope()
	if loopBody {
		e.loopCleanupMarks = append(e.loopCleanupMarks, scopeIndex)
	}
	var out []string
	for _, statement := range statements {
		lines, err := e.emitStatementWithComment(statement)
		if err != nil {
			return nil, err
		}
		out = append(out, lines...)
	}
	out = append(out, e.deferredCleanupLines(scopeIndex)...)
	if loopBody {
		e.loopCleanupMarks = e.loopCleanupMarks[:len(e.loopCleanupMarks)-1]
	}
	e.popDeferScope()
	return out, nil
}

func (e *cEmitter) pushDeferScope() int {
	e.deferScopes = append(e.deferScopes, deferScope{})
	return len(e.deferScopes) - 1
}

func (e *cEmitter) popDeferScope() {
	e.deferScopes = e.deferScopes[:len(e.deferScopes)-1]
}

func (e *cEmitter) addDeferCleanup(line string) {
	if len(e.deferScopes) == 0 {
		return
	}
	current := len(e.deferScopes) - 1
	e.deferScopes[current].cleanups = append(e.deferScopes[current].cleanups, line)
}

func (e *cEmitter) deferredCleanupLines(start int) []string {
	var lines []string
	if start < 0 {
		start = 0
	}
	for scopeIndex := len(e.deferScopes) - 1; scopeIndex >= start; scopeIndex-- {
		scope := e.deferScopes[scopeIndex]
		for i := len(scope.cleanups) - 1; i >= 0; i-- {
			lines = append(lines, scope.cleanups[i])
		}
	}
	return lines
}

func (e *cEmitter) emitStatementWithComment(statement ast.Statement) ([]string, error) {
	lines, err := e.emitStatement(statement)
	if err != nil {
		return nil, err
	}
	return prependSourceComment(statement.Loc(), lines), nil
}

func (e *cEmitter) emitStatement(statement ast.Statement) ([]string, error) {
	switch s := statement.(type) {
	case *ast.VarDecl:
		return e.emitVarDecl(s)
	case *ast.Assignment:
		target, err := e.emitExpression(s.Target)
		if err != nil {
			return nil, err
		}
		value, err := e.emitExpression(s.Value)
		if err != nil {
			return nil, err
		}
		return []string{fmt.Sprintf("%s = %s;", target, value)}, nil
	case *ast.Out:
		line, err := e.emitOut(s.Value)
		return []string{line}, err
	case *ast.Do:
		return e.emitDo(s)
	case *ast.Defer:
		return e.emitDefer(s)
	case *ast.Assert:
		return e.emitAssert(s)
	case *ast.Return:
		value, err := e.emitExpression(s.Value)
		if err != nil {
			return nil, err
		}
		lines := e.deferredCleanupLines(0)
		lines = append(lines, fmt.Sprintf("return %s;", value))
		return lines, nil
	case *ast.If:
		return e.emitIf(s)
	case *ast.While:
		return e.emitWhile(s)
	case *ast.Repeat:
		return e.emitRepeat(s)
	case *ast.For:
		return e.emitFor(s)
	case *ast.Break:
		lines := e.deferredCleanupLines(e.currentLoopCleanupMark())
		lines = append(lines, "break;")
		return lines, nil
	case *ast.Continue:
		lines := e.deferredCleanupLines(e.currentLoopCleanupMark())
		lines = append(lines, "continue;")
		return lines, nil
	default:
		return nil, errorAt(statement.Loc(), "internal error: unknown statement")
	}
}

func (e *cEmitter) emitDo(statement *ast.Do) ([]string, error) {
	call, ok := statement.Value.(*ast.Call)
	if !ok {
		return nil, errorAt(statement.Location, "internal error: do has non-call value")
	}
	rendered, err := e.emitCall(call)
	if err != nil {
		return nil, err
	}
	return []string{rendered + ";"}, nil
}

func (e *cEmitter) emitDefer(statement *ast.Defer) ([]string, error) {
	call, ok := statement.Value.(*ast.Call)
	if !ok {
		return nil, errorAt(statement.Location, "internal error: defer has non-call value")
	}
	fn, ok := builtins.LookupQualified(call.Callee)
	if !ok || !fn.Effect {
		return nil, errorAt(statement.Location, "internal error: defer has non-effect call")
	}
	var lines []string
	args := make([]string, 0, len(call.Args))
	for index, arg := range call.Args {
		rendered, err := e.emitExpression(arg)
		if err != nil {
			return nil, err
		}
		temp := e.nextTemp(fmt.Sprintf("__defer_%s_%d", strings.ReplaceAll(call.Callee, ".", "_"), index+1))
		decl, err := cDecl(arg.ExprType(), temp, true)
		if err != nil {
			return nil, err
		}
		lines = append(lines, fmt.Sprintf("%s = %s;", decl, rendered))
		args = append(args, temp)
	}
	e.addDeferCleanup(fmt.Sprintf("%s(%s);", fn.CName, strings.Join(args, ", ")))
	return lines, nil
}

func (e *cEmitter) currentLoopCleanupMark() int {
	if len(e.loopCleanupMarks) == 0 {
		return len(e.deferScopes)
	}
	return e.loopCleanupMarks[len(e.loopCleanupMarks)-1]
}

func (e *cEmitter) emitTestDecl(test *ast.TestDecl) ([]string, error) {
	lines := []string{
		"walk_tests++;",
		fmt.Sprintf("printf(\"test: %s\\n\");", escapeCTestName(test.Name)),
		"{",
	}
	body, err := e.emitBlock(test.Body)
	if err != nil {
		return nil, err
	}
	lines = appendIndented(lines, body)
	lines = append(lines, "}")
	return lines, nil
}

func (e *cEmitter) emitAssert(statement *ast.Assert) ([]string, error) {
	value, err := e.emitExpression(statement.Value)
	if err != nil {
		return nil, err
	}
	return []string{
		fmt.Sprintf("if (!(%s)) {", value),
		fmt.Sprintf("    printf(\"FAIL %s:%d:%d\\n\");", escapeCString(statement.Location.Filename), statement.Location.Line, statement.Location.Column),
		"    walk_failures++;",
		"}",
	}, nil
}

func (e *cEmitter) emitVarDecl(statement *ast.VarDecl) ([]string, error) {
	typeName := statement.Value.ExprType()
	if statement.Annotation.Kind != ast.TypeInvalid {
		typeName = statement.Annotation
	}
	array, ok := statement.Value.(*ast.ArrayLiteral)
	if ok {
		return e.emitArrayDecl(statement.Name, typeName, array, statement.Mutable)
	}
	value, err := e.emitExpression(statement.Value)
	if err != nil {
		return nil, err
	}
	decl, err := cDecl(typeName, statement.Name, statement.Mutable)
	if err != nil {
		return nil, err
	}
	return []string{fmt.Sprintf("%s = %s;", decl, value)}, nil
}

func (e *cEmitter) emitArrayDecl(name string, typeName ast.Type, array *ast.ArrayLiteral, mutable bool) ([]string, error) {
	if typeName.Kind != ast.TypeArray || typeName.Elem == nil {
		return nil, errorAt(array.Loc(), "internal error: array literal has non-array type")
	}
	itemName := e.nextTemp(name + "_items")
	itemType, err := cArrayItemType(*typeName.Elem)
	if err != nil {
		return nil, err
	}
	values := make([]string, 0, len(array.Elements))
	for _, element := range array.Elements {
		value, err := e.emitExpression(element)
		if err != nil {
			return nil, err
		}
		values = append(values, value)
	}
	decl, err := cDecl(typeName, name, mutable)
	if err != nil {
		return nil, err
	}
	lines := []string{
		fmt.Sprintf("%s *%s = (%s *)walk_rt_alloc_array(%d, sizeof(%s));", itemType, itemName, itemType, len(values), itemType),
	}
	for i, value := range values {
		lines = append(lines, fmt.Sprintf("%s[%d] = %s;", itemName, i, value))
	}
	lines = append(lines, fmt.Sprintf("%s = {%s, %d};", decl, itemName, len(values)))
	return lines, nil
}

func (e *cEmitter) emitIf(statement *ast.If) ([]string, error) {
	cond, err := e.emitExpression(statement.Cond)
	if err != nil {
		return nil, err
	}
	lines := []string{fmt.Sprintf("if (%s) {", cond)}
	e.indent++
	thenLines, err := e.emitBlock(statement.Then)
	e.indent--
	if err != nil {
		return nil, err
	}
	lines = appendIndented(lines, thenLines)
	if len(statement.Else) == 0 {
		lines = append(lines, "}")
		return lines, nil
	}
	lines = append(lines, "} else {")
	e.indent++
	elseLines, err := e.emitBlock(statement.Else)
	e.indent--
	if err != nil {
		return nil, err
	}
	lines = appendIndented(lines, elseLines)
	lines = append(lines, "}")
	return lines, nil
}

func (e *cEmitter) emitWhile(statement *ast.While) ([]string, error) {
	cond, err := e.emitExpression(statement.Cond)
	if err != nil {
		return nil, err
	}
	lines := []string{fmt.Sprintf("while (%s) {", cond)}
	e.indent++
	body, err := e.emitLoopBlock(statement.Body)
	e.indent--
	if err != nil {
		return nil, err
	}
	lines = appendIndented(lines, body)
	lines = append(lines, "}")
	return lines, nil
}

func (e *cEmitter) emitRepeat(statement *ast.Repeat) ([]string, error) {
	count, err := e.emitExpression(statement.Count)
	if err != nil {
		return nil, err
	}
	i := e.nextTemp("__repeat")
	lines := []string{fmt.Sprintf("for (long long %s = 0; %s < (%s); %s++) {", i, i, count, i)}
	e.indent++
	body, err := e.emitLoopBlock(statement.Body)
	e.indent--
	if err != nil {
		return nil, err
	}
	lines = appendIndented(lines, body)
	lines = append(lines, "}")
	return lines, nil
}

func (e *cEmitter) emitFor(statement *ast.For) ([]string, error) {
	iterable, err := e.emitExpression(statement.Iterable)
	if err != nil {
		return nil, err
	}
	itemType, err := cArrayItemType(*statement.Iterable.ExprType().Elem)
	if err != nil {
		return nil, err
	}
	i := e.nextTemp("__for")
	lines := []string{fmt.Sprintf("for (long long %s = 0; %s < %s.len; %s++) {", i, i, iterable, i)}
	lines = append(lines, fmt.Sprintf("    %s %s = %s.items[%s];", itemType, statement.Name, iterable, i))
	e.indent++
	body, err := e.emitLoopBlock(statement.Body)
	e.indent--
	if err != nil {
		return nil, err
	}
	lines = appendIndented(lines, body)
	lines = append(lines, "}")
	return lines, nil
}

func appendIndented(lines []string, nested []string) []string {
	for _, line := range nested {
		lines = append(lines, "    "+line)
	}
	return lines
}

func prependSourceComment(location ast.Location, lines []string) []string {
	if location.Line == 0 {
		return lines
	}
	return append([]string{fmt.Sprintf("/* source: %s:%d:%d */", filepath.Base(location.Filename), location.Line, location.Column)}, lines...)
}

func (e *cEmitter) emitOut(expression ast.Expression) (string, error) {
	value, err := e.emitExpression(expression)
	if err != nil {
		return "", err
	}
	switch expression.ExprType().Kind {
	case ast.TypeInt:
		return fmt.Sprintf("walk_rt_print_int((WalkInt)(%s));", value), nil
	case ast.TypeFloat:
		return fmt.Sprintf("walk_rt_print_float((WalkFloat)(%s));", value), nil
	case ast.TypeBool:
		return fmt.Sprintf("walk_rt_print_bool((WalkBool)(%s));", value), nil
	case ast.TypeString:
		return fmt.Sprintf("walk_rt_print_string((WalkString)(%s));", value), nil
	default:
		return "", errorAt(expression.Loc(), "internal error: cannot print %s", expression.ExprType().String())
	}
}

func (e *cEmitter) emitExpression(expression ast.Expression) (string, error) {
	switch ex := expression.(type) {
	case *ast.Literal:
		return emitLiteral(ex)
	case *ast.InterpolatedString:
		return e.emitInterpolatedString(ex)
	case *ast.Name:
		if e.currentModule != "" && e.moduleFunctionNames[e.currentModule][ex.Identifier] {
			return mangleModuleName(e.currentModule, ex.Identifier), nil
		}
		return ex.Identifier, nil
	case *ast.Prefix:
		return e.emitPrefix(ex)
	case *ast.Call:
		return e.emitCall(ex)
	case *ast.Input:
		prompt := "NULL"
		if ex.Prompt != nil {
			rendered, err := e.emitExpression(ex.Prompt)
			if err != nil {
				return "", err
			}
			prompt = rendered
		}
		return fmt.Sprintf("walk_rt_input_line(%s)", prompt), nil
	case *ast.Index:
		target, err := e.emitExpression(ex.Target)
		if err != nil {
			return "", err
		}
		index, err := e.emitExpression(ex.Index)
		if err != nil {
			return "", err
		}
		if ex.Target.ExprType().Kind == ast.TypeString {
			return fmt.Sprintf("walk_rt_string_at(%s, %s)", target, index), nil
		}
		return fmt.Sprintf("%s.items[%s]", target, index), nil
	case *ast.FieldAccess:
		target, err := e.emitExpression(ex.Target)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("(%s).%s", target, ex.Field), nil
	case *ast.ArrayLiteral:
		return "", errorAt(ex.Loc(), "internal error: array literal cannot be emitted inline")
	default:
		return "", errorAt(expression.Loc(), "internal error: unknown expression")
	}
}

func (e *cEmitter) emitInterpolatedString(expression *ast.InterpolatedString) (string, error) {
	value := `""`
	for _, part := range expression.Parts {
		var rendered string
		if part.Expression == nil {
			rendered = `"` + escapeCString(part.Literal) + `"`
		} else {
			expr, err := e.emitExpression(part.Expression)
			if err != nil {
				return "", err
			}
			rendered, err = e.emitInterpolatedExpression(part.Expression, expr)
			if err != nil {
				return "", err
			}
		}
		value = fmt.Sprintf("walk_rt_string_concat(%s, %s)", value, rendered)
	}
	return value, nil
}

func (e *cEmitter) emitInterpolatedExpression(expression ast.Expression, rendered string) (string, error) {
	switch expression.ExprType().Kind {
	case ast.TypeInt:
		return fmt.Sprintf("walk_rt_format_int((WalkInt)(%s))", rendered), nil
	case ast.TypeFloat:
		return fmt.Sprintf("walk_rt_format_float((WalkFloat)(%s))", rendered), nil
	case ast.TypeBool:
		return fmt.Sprintf("walk_rt_format_bool((WalkBool)(%s))", rendered), nil
	case ast.TypeString:
		return fmt.Sprintf("walk_rt_format_string((WalkString)(%s))", rendered), nil
	default:
		return "", errorAt(expression.Loc(), "internal error: cannot interpolate %s", expression.ExprType().String())
	}
}

func emitLiteral(literal *ast.Literal) (string, error) {
	switch literal.Kind {
	case ast.LiteralInt, ast.LiteralFloat:
		return literal.Value, nil
	case ast.LiteralBool:
		return literal.Value, nil
	case ast.LiteralString:
		return `"` + escapeCString(literal.Value) + `"`, nil
	case ast.LiteralNull:
		return "NULL", nil
	default:
		return "", errorAt(literal.Loc(), "internal error: unsupported literal")
	}
}

func (e *cEmitter) emitPrefix(expression *ast.Prefix) (string, error) {
	var args []string
	for _, arg := range expression.Args {
		rendered, err := e.emitExpression(arg)
		if err != nil {
			return "", err
		}
		args = append(args, rendered)
	}

	switch expression.Operator {
	case "+", "*":
		return "(" + strings.Join(args, " "+expression.Operator+" ") + ")", nil
	case "and":
		return "(" + strings.Join(args, " && ") + ")", nil
	case "or":
		return "(" + strings.Join(args, " || ") + ")", nil
	case "not":
		return "(!" + args[0] + ")", nil
	case "-":
		return fmt.Sprintf("(%s - %s)", args[0], args[1]), nil
	case "/":
		return fmt.Sprintf("((double)(%s) / (%s))", args[0], args[1]), nil
	case ">", "<", ">=", "<=", "==", "!=":
		if expression.Args[0].ExprType().Kind == ast.TypeString && expression.Args[1].ExprType().Kind == ast.TypeString {
			comparison := "=="
			if expression.Operator == "!=" {
				comparison = "!="
			}
			if expression.Operator == "==" || expression.Operator == "!=" {
				return fmt.Sprintf("(strcmp(%s, %s) %s 0)", args[0], args[1], comparison), nil
			}
		}
		return fmt.Sprintf("(%s %s %s)", args[0], expression.Operator, args[1]), nil
	case "^":
		return fmt.Sprintf("pow(%s, %s)", args[0], args[1]), nil
	default:
		return "", errorAt(expression.Loc(), "internal error: unsupported operator %s", expression.Operator)
	}
}

func (e *cEmitter) emitCall(call *ast.Call) (string, error) {
	args := make([]string, 0, len(call.Args))
	for _, arg := range call.Args {
		rendered, err := e.emitExpression(arg)
		if err != nil {
			return "", err
		}
		args = append(args, rendered)
	}
	if call.ExprType().Kind == ast.TypeStruct && call.Callee == call.ExprType().Name {
		def := e.structs[call.Callee]
		if def == nil {
			return "", errorAt(call.Loc(), "internal error: unknown struct %s", call.Callee)
		}
		fields := make([]string, 0, len(def.Fields))
		for i, field := range def.Fields {
			fields = append(fields, fmt.Sprintf(".%s = %s", field.Name, args[i]))
		}
		return fmt.Sprintf("(%s){%s}", cStructName(call.Callee), strings.Join(fields, ", ")), nil
	}
	if call.Receiver != nil && call.Method != "" && call.Receiver.ExprType().Kind == ast.TypeStruct {
		receiver, err := e.emitExpression(call.Receiver)
		if err != nil {
			return "", err
		}
		args = append([]string{receiver}, args...)
		return fmt.Sprintf("%s(%s)", cMethodName(call.Receiver.ExprType().Name, call.Method), strings.Join(args, ", ")), nil
	}
	if len(call.TypeArgs) > 0 {
		callee := call.Callee
		if e.currentModule != "" && !strings.Contains(callee, ".") {
			callee = e.currentModule + "." + callee
		}
		return fmt.Sprintf("%s(%s)", genericInstanceName(callee, call.TypeArgs), strings.Join(args, ", ")), nil
	}
	if fn, ok := builtins.LookupQualified(call.Callee); ok {
		return fmt.Sprintf("%s(%s)", fn.CName, strings.Join(args, ", ")), nil
	}
	switch call.Callee {
	case "math.sqrt":
		return fmt.Sprintf("sqrt(%s)", strings.Join(args, ", ")), nil
	case "math.pow":
		return fmt.Sprintf("pow(%s)", strings.Join(args, ", ")), nil
	case "string.len":
		return fmt.Sprintf("walk_rt_string_len(%s)", args[0]), nil
	case "string.at":
		return fmt.Sprintf("walk_rt_string_at(%s, %s)", args[0], args[1]), nil
	case "string.contains":
		return fmt.Sprintf("walk_rt_string_contains(%s, %s)", args[0], args[1]), nil
	case "string.concat":
		return fmt.Sprintf("walk_rt_string_concat(%s, %s)", args[0], args[1]), nil
	case "array.len":
		return fmt.Sprintf("%s.len", args[0]), nil
	case "array.contains":
		suffix, err := nativeArrayHelperSuffix(*call.Args[0].ExprType().Elem)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("walk_rt_array_contains_%s(%s, %s)", suffix, args[0], args[1]), nil
	case "array.push":
		suffix, err := nativeArrayHelperSuffix(*call.Args[0].ExprType().Elem)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("walk_rt_array_push_%s(%s, %s)", suffix, args[0], args[1]), nil
	case "time.now":
		return "(long long)time(NULL)", nil
	case "random.int":
		return fmt.Sprintf("walk_rt_random_int(%s)", strings.Join(args, ", ")), nil
	case "random.choice":
		suffix, err := nativeArrayHelperSuffix(*call.Args[0].ExprType().Elem)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("walk_rt_array_choice_%s(%s)", suffix, args[0]), nil
	case "testing.assert":
		return args[0], nil
	default:
		if strings.Contains(call.Callee, ".") {
			return fmt.Sprintf("%s(%s)", strings.ReplaceAll(call.Callee, ".", "__"), strings.Join(args, ", ")), nil
		}
		if e.currentModule != "" && e.moduleFunctionNames[e.currentModule][call.Callee] {
			return fmt.Sprintf("%s(%s)", mangleModuleName(e.currentModule, call.Callee), strings.Join(args, ", ")), nil
		}
		return fmt.Sprintf("%s(%s)", call.Callee, strings.Join(args, ", ")), nil
	}
}

func (e *cEmitter) cFunctionDeclName(fn *ast.FuncDecl) string {
	if fn.CName != "" {
		return fn.CName
	}
	if fn.Receiver != "" {
		return cMethodName(fn.Receiver, fn.Name)
	}
	return e.cFunctionName(fn.Name)
}

func (e *cEmitter) cFunctionName(name string) string {
	if e.currentModule == "" {
		return name
	}
	return mangleModuleName(e.currentModule, name)
}

func mangleModuleName(module string, name string) string {
	return strings.ReplaceAll(module, ".", "__") + "__" + name
}

func cMethodName(receiver string, name string) string {
	return receiver + "__" + name
}

func cReturnType(typeName ast.Type) (string, error) {
	if typeName.Kind == ast.TypeVoid {
		return "void", nil
	}
	return cValueType(typeName)
}

func cDecl(typeName ast.Type, name string, mutable bool) (string, error) {
	if typeName.Kind == ast.TypeFunction {
		if typeName.Return == nil {
			return "", fmt.Errorf("internal error: function type needs return")
		}
		ret, err := cReturnType(*typeName.Return)
		if err != nil {
			return "", err
		}
		params := make([]string, 0, len(typeName.Params))
		for _, param := range typeName.Params {
			rendered, err := cValueType(param)
			if err != nil {
				return "", err
			}
			params = append(params, rendered)
		}
		if len(params) == 0 {
			params = append(params, "void")
		}
		return fmt.Sprintf("%s (*%s)(%s)", ret, name, strings.Join(params, ", ")), nil
	}
	valueType, err := cValueType(typeName)
	if err != nil {
		return "", err
	}
	if mutable || typeName.Nullable {
		return valueType + " " + name, nil
	}
	return "const " + valueType + " " + name, nil
}

func cValueType(typeName ast.Type) (string, error) {
	switch typeName.Kind {
	case ast.TypeInt:
		return "WalkInt", nil
	case ast.TypeFloat:
		return "WalkFloat", nil
	case ast.TypeBool:
		return "WalkBool", nil
	case ast.TypeString:
		return "WalkString", nil
	case ast.TypeStruct:
		return cStructName(typeName.Name), nil
	case ast.TypeArray:
		if typeName.Elem == nil {
			return "", fmt.Errorf("internal error: array type needs element")
		}
		switch typeName.Elem.Kind {
		case ast.TypeInt:
			return "WalkArrayInt", nil
		case ast.TypeFloat:
			return "WalkArrayFloat", nil
		case ast.TypeBool:
			return "WalkArrayBool", nil
		case ast.TypeString:
			return "WalkArrayString", nil
		case ast.TypeStruct:
			return cStructArrayName(typeName.Elem.Name), nil
		}
	}
	return "", fmt.Errorf("internal error: unsupported C type %s", typeName.String())
}

func cArrayItemType(typeName ast.Type) (string, error) {
	switch typeName.Kind {
	case ast.TypeInt:
		return "WalkInt", nil
	case ast.TypeFloat:
		return "WalkFloat", nil
	case ast.TypeBool:
		return "WalkBool", nil
	case ast.TypeString:
		return "WalkString", nil
	case ast.TypeStruct:
		return cStructName(typeName.Name), nil
	default:
		return "", fmt.Errorf("internal error: unsupported array element type %s", typeName.String())
	}
}

func nativeArrayHelperSuffix(typeName ast.Type) (string, error) {
	switch typeName.Kind {
	case ast.TypeInt:
		return "int", nil
	case ast.TypeFloat:
		return "float", nil
	case ast.TypeBool:
		return "bool", nil
	case ast.TypeString:
		return "string", nil
	default:
		return "", fmt.Errorf("internal error: unsupported native array helper type %s", typeName.String())
	}
}

func cStructName(name string) string {
	return name
}

func cStructArrayName(name string) string {
	return "WalkArray" + name
}

func (e *cEmitter) nextTemp(prefix string) string {
	e.tempID++
	clean := strings.ReplaceAll(prefix, ".", "_")
	return fmt.Sprintf("__%s_%d", clean, e.tempID)
}

func (e *cEmitter) indentString() string {
	return strings.Repeat("    ", e.indent)
}

func escapeCString(value string) string {
	replacer := strings.NewReplacer("\\", "\\\\", "\"", "\\\"", "\n", "\\n", "\t", "\\t")
	return replacer.Replace(value)
}

func escapeCTestName(value string) string {
	return escapeCString(value)
}

func errorAt(location ast.Location, format string, args ...any) error {
	return diagnostic.Errorf(location, format, args...)
}
