/* Generated by WalkLang. C is the primary backend and is intended to stay inspectable. */

#include <errno.h>
#include <limits.h>
#include <math.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <time.h>

#if defined(_WIN32)
#include <direct.h>
#include <process.h>
#include <windows.h>
#else
#include <dirent.h>
#include <sys/time.h>
#include <unistd.h>
#endif

/* walk runtime: no user pointers; array storage is runtime-owned for the process lifetime. */
typedef long long WalkInt;
typedef double WalkFloat;
typedef bool WalkBool;
typedef const char *WalkString;
typedef long long WalkSize;

typedef struct { WalkInt *items; WalkSize len; } WalkArrayInt;
typedef struct { WalkFloat *items; WalkSize len; } WalkArrayFloat;
typedef struct { WalkBool *items; WalkSize len; } WalkArrayBool;
typedef struct { WalkString *items; WalkSize len; } WalkArrayString;

static int __walk_host_argc = 0;
static char **__walk_host_argv = NULL;

#if defined(__GNUC__) || defined(__clang__)
#define WALK_UNUSED __attribute__((unused))
#else
#define WALK_UNUSED
#endif

typedef struct {
    WalkBool ok;
    WalkBool value;
    WalkString error;
} FileActionResult;
typedef struct { FileActionResult *items; WalkSize len; } WalkArrayFileActionResult;

typedef struct {
    WalkBool ok;
    WalkString value;
    WalkString error;
} FileReadResult;
typedef struct { FileReadResult *items; WalkSize len; } WalkArrayFileReadResult;

typedef struct {
    WalkBool ok;
    WalkString value;
    WalkString error;
} IOReadResult;
typedef struct { IOReadResult *items; WalkSize len; } WalkArrayIOReadResult;

typedef struct {
    WalkBool ok;
    WalkBool value;
    WalkString error;
} ParseBoolResult;
typedef struct { ParseBoolResult *items; WalkSize len; } WalkArrayParseBoolResult;

typedef struct {
    WalkBool ok;
    WalkFloat value;
    WalkString error;
} ParseFloatResult;
typedef struct { ParseFloatResult *items; WalkSize len; } WalkArrayParseFloatResult;

typedef struct {
    WalkBool ok;
    WalkInt value;
    WalkString error;
} ParseIntResult;
typedef struct { ParseIntResult *items; WalkSize len; } WalkArrayParseIntResult;

static WALK_UNUSED void *__walk_alloc_array(WalkSize len, size_t item_size) {
    if (len <= 0) { return NULL; }
    void *items = calloc((size_t)len, item_size);
    if (items == NULL) {
        fprintf(stderr, "walk runtime error: out of memory\n");
        exit(1);
    }
    return items;
}

static WALK_UNUSED void __walk_runtime_error(const char *message) {
    fprintf(stderr, "walk runtime error: %s\n", message);
    exit(1);
}

static unsigned long long __walk_random_state = 0;

static WALK_UNUSED unsigned long long __walk_random_seed(void) {
    unsigned long long seed = (unsigned long long)time(NULL);
    seed ^= ((unsigned long long)clock() << 32);
    seed ^= (unsigned long long)(uintptr_t)&seed;
#if defined(_WIN32)
    seed ^= ((unsigned long long)_getpid() << 16);
#else
    struct timeval tv;
    if (gettimeofday(&tv, NULL) == 0) {
        seed ^= ((unsigned long long)tv.tv_sec << 32) ^ (unsigned long long)tv.tv_usec;
    }
    seed ^= ((unsigned long long)getpid() << 16);
#endif
    if (seed == 0) { seed = 0x9e3779b97f4a7c15ULL; }
    return seed;
}

static WALK_UNUSED unsigned long long __walk_random_next(void) {
    if (__walk_random_state == 0) { __walk_random_state = __walk_random_seed(); }
    unsigned long long x = __walk_random_state;
    x ^= x >> 12;
    x ^= x << 25;
    x ^= x >> 27;
    __walk_random_state = x;
    return x * 2685821657736338717ULL;
}

static WALK_UNUSED WalkInt __walk_random_int(WalkInt min, WalkInt max) {
    if (max < min) { return min; }
    return min + (WalkInt)(__walk_random_next() % (unsigned long long)(max - min + 1));
}

static WALK_UNUSED WalkSize __walk_random_index(WalkSize len) {
    if (len <= 0) { __walk_runtime_error("random.choice on empty array"); }
    return (WalkSize)(__walk_random_next() % (unsigned long long)len);
}

static WALK_UNUSED WalkInt __walk_string_len(WalkString value) {
    return value == NULL ? 0 : (WalkInt)strlen(value);
}

static WALK_UNUSED WalkString __walk_string_at(WalkString value, WalkInt index) {
    WalkSize len = (WalkSize)__walk_string_len(value);
    if (index < 0 || index >= len) { __walk_runtime_error("string index out of range"); }
    char *out = (char *)malloc(2);
    if (out == NULL) { __walk_runtime_error("out of memory"); }
    out[0] = value[index];
    out[1] = '\0';
    return out;
}

static WALK_UNUSED WalkBool __walk_string_contains(WalkString text, WalkString item) {
    if (text == NULL) { text = ""; }
    if (item == NULL) { item = ""; }
    return strstr(text, item) != NULL;
}

static WALK_UNUSED WalkString __walk_string_concat(WalkString left, WalkString right) {
    if (left == NULL) { left = ""; }
    if (right == NULL) { right = ""; }
    size_t left_len = strlen(left);
    size_t right_len = strlen(right);
    if (left_len > ((size_t)-1) - right_len - 1) { __walk_runtime_error("out of memory"); }
    char *out = (char *)malloc(left_len + right_len + 1);
    if (out == NULL) { __walk_runtime_error("out of memory"); }
    memcpy(out, left, left_len);
    memcpy(out + left_len, right, right_len);
    out[left_len + right_len] = '\0';
    return out;
}

static WALK_UNUSED WalkString __walk_format_int(WalkInt value) {
    char buffer[64];
    int len = snprintf(buffer, sizeof(buffer), "%lld", (long long)value);
    if (len < 0 || (size_t)len >= sizeof(buffer)) { __walk_runtime_error("format failed"); }
    char *out = (char *)malloc((size_t)len + 1);
    if (out == NULL) { __walk_runtime_error("out of memory"); }
    memcpy(out, buffer, (size_t)len + 1);
    return out;
}

static WALK_UNUSED WalkString __walk_format_float(WalkFloat value) {
    char buffer[64];
    int len = snprintf(buffer, sizeof(buffer), "%g", (double)value);
    if (len < 0 || (size_t)len >= sizeof(buffer)) { __walk_runtime_error("format failed"); }
    char *out = (char *)malloc((size_t)len + 1);
    if (out == NULL) { __walk_runtime_error("out of memory"); }
    memcpy(out, buffer, (size_t)len + 1);
    return out;
}

static WALK_UNUSED WalkString __walk_format_bool(WalkBool value) {
    return value ? "true" : "false";
}

static WALK_UNUSED WalkString __walk_format_string(WalkString value) {
    return value == NULL ? "null" : value;
}

static WALK_UNUSED WalkString __walk_copy_string(const char *value) {
    if (value == NULL) { value = ""; }
    size_t len = strlen(value);
    char *out = (char *)malloc(len + 1);
    if (out == NULL) { __walk_runtime_error("out of memory"); }
    memcpy(out, value, len + 1);
    return out;
}

static WALK_UNUSED WalkArrayInt __walk_array_push_int(WalkArrayInt array, WalkInt item) {
    WalkInt *items = (WalkInt *)__walk_alloc_array(array.len + 1, sizeof(WalkInt));
    for (WalkSize i = 0; i < array.len; i++) { items[i] = array.items[i]; }
    items[array.len] = item;
    return (WalkArrayInt){items, array.len + 1};
}

static WALK_UNUSED WalkArrayFloat __walk_array_push_float(WalkArrayFloat array, WalkFloat item) {
    WalkFloat *items = (WalkFloat *)__walk_alloc_array(array.len + 1, sizeof(WalkFloat));
    for (WalkSize i = 0; i < array.len; i++) { items[i] = array.items[i]; }
    items[array.len] = item;
    return (WalkArrayFloat){items, array.len + 1};
}

static WALK_UNUSED WalkArrayBool __walk_array_push_bool(WalkArrayBool array, WalkBool item) {
    WalkBool *items = (WalkBool *)__walk_alloc_array(array.len + 1, sizeof(WalkBool));
    for (WalkSize i = 0; i < array.len; i++) { items[i] = array.items[i]; }
    items[array.len] = item;
    return (WalkArrayBool){items, array.len + 1};
}

static WALK_UNUSED WalkArrayString __walk_array_push_string(WalkArrayString array, WalkString item) {
    WalkString *items = (WalkString *)__walk_alloc_array(array.len + 1, sizeof(WalkString));
    for (WalkSize i = 0; i < array.len; i++) { items[i] = array.items[i]; }
    items[array.len] = item;
    return (WalkArrayString){items, array.len + 1};
}

static WALK_UNUSED WalkBool __walk_array_contains_int(WalkArrayInt array, WalkInt item) {
    for (WalkSize i = 0; i < array.len; i++) { if (array.items[i] == item) { return true; } }
    return false;
}

static WALK_UNUSED WalkBool __walk_array_contains_float(WalkArrayFloat array, WalkFloat item) {
    for (WalkSize i = 0; i < array.len; i++) { if (array.items[i] == item) { return true; } }
    return false;
}

static WALK_UNUSED WalkBool __walk_array_contains_bool(WalkArrayBool array, WalkBool item) {
    for (WalkSize i = 0; i < array.len; i++) { if (array.items[i] == item) { return true; } }
    return false;
}

static WALK_UNUSED WalkBool __walk_array_contains_string(WalkArrayString array, WalkString item) {
    for (WalkSize i = 0; i < array.len; i++) { if (strcmp(array.items[i], item) == 0) { return true; } }
    return false;
}

static WALK_UNUSED WalkInt __walk_array_choice_int(WalkArrayInt array) { return array.items[__walk_random_index(array.len)]; }
static WALK_UNUSED WalkFloat __walk_array_choice_float(WalkArrayFloat array) { return array.items[__walk_random_index(array.len)]; }
static WALK_UNUSED WalkBool __walk_array_choice_bool(WalkArrayBool array) { return array.items[__walk_random_index(array.len)]; }
static WALK_UNUSED WalkString __walk_array_choice_string(WalkArrayString array) { return array.items[__walk_random_index(array.len)]; }

static WALK_UNUSED WalkString __walk_input(WalkString prompt) {
    if (prompt != NULL) {
        fputs(prompt, stdout);
        fflush(stdout);
    }
    size_t cap = 64;
    size_t len = 0;
    char *buffer = (char *)malloc(cap);
    if (buffer == NULL) {
        fprintf(stderr, "walk runtime error: out of memory\n");
        exit(1);
    }
    for (;;) {
        int ch = fgetc(stdin);
        if (ch == EOF) {
            if (ferror(stdin)) {
                free(buffer);
                fprintf(stderr, "walk runtime error: stdin read failed\n");
                exit(1);
            }
            if (len == 0) {
                free(buffer);
                fprintf(stderr, "walk runtime error: input reached EOF\n");
                exit(1);
            }
            break;
        }
        if (ch == '\n') { break; }
        if (ch == '\r') {
            int next = fgetc(stdin);
            if (next == '\n') { break; }
            if (next == EOF && ferror(stdin)) {
                free(buffer);
                fprintf(stderr, "walk runtime error: stdin read failed\n");
                exit(1);
            }
            if (next != EOF) { ungetc(next, stdin); }
        }
        if (len + 1 >= cap) {
            if (cap > ((size_t)-1) / 2) {
                free(buffer);
                fprintf(stderr, "walk runtime error: out of memory\n");
                exit(1);
            }
            size_t next_cap = cap * 2;
            char *next_buffer = (char *)realloc(buffer, next_cap);
            if (next_buffer == NULL) {
                free(buffer);
                fprintf(stderr, "walk runtime error: out of memory\n");
                exit(1);
            }
            buffer = next_buffer;
            cap = next_cap;
        }
        buffer[len++] = (char)ch;
    }
    buffer[len] = '\0';
    return buffer;
}

static WALK_UNUSED void __walk_print_int(WalkInt value) { printf("%lld\n", (long long)value); }
static WALK_UNUSED void __walk_print_float(WalkFloat value) { printf("%g\n", (double)value); }
static WALK_UNUSED void __walk_print_bool(WalkBool value) { printf("%s\n", value ? "true" : "false"); }
static WALK_UNUSED void __walk_print_string(WalkString value) { printf("%s\n", value == NULL ? "null" : value); }

static WALK_UNUSED void __walk_io_write(WalkString value) {
    fputs(value == NULL ? "null" : value, stdout);
    fflush(stdout);
}

static WALK_UNUSED void __walk_io_write_line(WalkString value) {
    fprintf(stdout, "%s\n", value == NULL ? "null" : value);
    fflush(stdout);
}

static WALK_UNUSED void __walk_io_error_line(WalkString value) {
    fprintf(stderr, "%s\n", value == NULL ? "null" : value);
    fflush(stderr);
}

static WALK_UNUSED IOReadResult __walk_io_read_ok(WalkString value) {
    return (IOReadResult){.ok = true, .value = value, .error = ""};
}

static WALK_UNUSED IOReadResult __walk_io_read_error(WalkString error) {
    return (IOReadResult){.ok = false, .value = "", .error = error};
}

static WALK_UNUSED IOReadResult __walk_io_read_line(void) {
    size_t cap = 64;
    size_t len = 0;
    char *buffer = (char *)malloc(cap);
    if (buffer == NULL) { __walk_runtime_error("out of memory"); }
    for (;;) {
        int ch = fgetc(stdin);
        if (ch == EOF) {
            if (ferror(stdin)) {
                free(buffer);
                return __walk_io_read_error("stdin read failed");
            }
            if (len == 0) {
                free(buffer);
                return __walk_io_read_error("eof");
            }
            break;
        }
        if (ch == '\n') { break; }
        if (ch == '\r') {
            int next = fgetc(stdin);
            if (next == '\n') { break; }
            if (next == EOF && ferror(stdin)) {
                free(buffer);
                return __walk_io_read_error("stdin read failed");
            }
            if (next != EOF) { ungetc(next, stdin); }
        }
        if (len + 1 >= cap) {
            if (cap > ((size_t)-1) / 2) {
                free(buffer);
                __walk_runtime_error("out of memory");
            }
            size_t next_cap = cap * 2;
            char *next_buffer = (char *)realloc(buffer, next_cap);
            if (next_buffer == NULL) {
                free(buffer);
                __walk_runtime_error("out of memory");
            }
            buffer = next_buffer;
            cap = next_cap;
        }
        buffer[len++] = (char)ch;
    }
    buffer[len] = '\0';
    return __walk_io_read_ok(buffer);
}

static WALK_UNUSED IOReadResult __walk_io_read_all(void) {
    size_t cap = 64;
    size_t len = 0;
    char *buffer = (char *)malloc(cap);
    if (buffer == NULL) { __walk_runtime_error("out of memory"); }
    for (;;) {
        int ch = fgetc(stdin);
        if (ch == EOF) {
            if (ferror(stdin)) {
                free(buffer);
                return __walk_io_read_error("stdin read failed");
            }
            break;
        }
        if (len + 1 >= cap) {
            if (cap > ((size_t)-1) / 2) {
                free(buffer);
                __walk_runtime_error("out of memory");
            }
            size_t next_cap = cap * 2;
            char *next_buffer = (char *)realloc(buffer, next_cap);
            if (next_buffer == NULL) {
                free(buffer);
                __walk_runtime_error("out of memory");
            }
            buffer = next_buffer;
            cap = next_cap;
        }
        buffer[len++] = (char)ch;
    }
    buffer[len] = '\0';
    return __walk_io_read_ok(buffer);
}

static WALK_UNUSED WalkBool __walk_utf8_cont(unsigned char ch) {
    return (ch & 0xC0) == 0x80;
}

static WALK_UNUSED WalkBool __walk_is_valid_utf8(WalkString text) {
    if (text == NULL) { return false; }
    const unsigned char *bytes = (const unsigned char *)text;
    size_t len = strlen(text);
    size_t i = 0;
    while (i < len) {
        unsigned char ch = bytes[i];
        if (ch <= 0x7F) { i++; continue; }
        if (ch >= 0xC2 && ch <= 0xDF) {
            if (i + 1 >= len || !__walk_utf8_cont(bytes[i + 1])) { return false; }
            i += 2;
            continue;
        }
        if (ch == 0xE0) {
            if (i + 2 >= len || bytes[i + 1] < 0xA0 || bytes[i + 1] > 0xBF || !__walk_utf8_cont(bytes[i + 2])) { return false; }
            i += 3;
            continue;
        }
        if ((ch >= 0xE1 && ch <= 0xEC) || (ch >= 0xEE && ch <= 0xEF)) {
            if (i + 2 >= len || !__walk_utf8_cont(bytes[i + 1]) || !__walk_utf8_cont(bytes[i + 2])) { return false; }
            i += 3;
            continue;
        }
        if (ch == 0xED) {
            if (i + 2 >= len || bytes[i + 1] < 0x80 || bytes[i + 1] > 0x9F || !__walk_utf8_cont(bytes[i + 2])) { return false; }
            i += 3;
            continue;
        }
        if (ch == 0xF0) {
            if (i + 3 >= len || bytes[i + 1] < 0x90 || bytes[i + 1] > 0xBF || !__walk_utf8_cont(bytes[i + 2]) || !__walk_utf8_cont(bytes[i + 3])) { return false; }
            i += 4;
            continue;
        }
        if (ch >= 0xF1 && ch <= 0xF3) {
            if (i + 3 >= len || !__walk_utf8_cont(bytes[i + 1]) || !__walk_utf8_cont(bytes[i + 2]) || !__walk_utf8_cont(bytes[i + 3])) { return false; }
            i += 4;
            continue;
        }
        if (ch == 0xF4) {
            if (i + 3 >= len || bytes[i + 1] < 0x80 || bytes[i + 1] > 0x8F || !__walk_utf8_cont(bytes[i + 2]) || !__walk_utf8_cont(bytes[i + 3])) { return false; }
            i += 4;
            continue;
        }
        return false;
    }
    return true;
}

static WALK_UNUSED WalkString __walk_file_read_try_value(WalkString path, WalkString *error) {
    *error = "";
    if (path == NULL || path[0] == '\0') { *error = "file path empty"; return ""; }
    FILE *file = fopen(path, "rb");
    if (file == NULL) { *error = "file read failed"; return ""; }
    size_t cap = 64;
    size_t len = 0;
    char *buffer = (char *)malloc(cap);
    if (buffer == NULL) {
        fclose(file);
        __walk_runtime_error("out of memory");
    }
    for (;;) {
        int ch = fgetc(file);
        if (ch == EOF) {
            if (ferror(file)) {
                fclose(file);
                free(buffer);
                *error = "file read failed";
                return "";
            }
            break;
        }
        if (ch == '\0') {
            fclose(file);
            free(buffer);
            *error = "file contains null byte";
            return "";
        }
        if (len + 1 >= cap) {
            if (cap > ((size_t)-1) / 2) {
                fclose(file);
                free(buffer);
                __walk_runtime_error("out of memory");
            }
            size_t next_cap = cap * 2;
            char *next_buffer = (char *)realloc(buffer, next_cap);
            if (next_buffer == NULL) {
                fclose(file);
                free(buffer);
                __walk_runtime_error("out of memory");
            }
            buffer = next_buffer;
            cap = next_cap;
        }
        buffer[len++] = (char)ch;
    }
    if (fclose(file) != 0) {
        free(buffer);
        *error = "file read failed";
        return "";
    }
    buffer[len] = '\0';
    if (!__walk_is_valid_utf8(buffer)) {
        free(buffer);
        *error = "file invalid utf-8";
        return "";
    }
    return buffer;
}

static WALK_UNUSED WalkString __walk_file_read(WalkString path) {
    WalkString error = "";
    WalkString value = __walk_file_read_try_value(path, &error);
    if (error[0] != '\0') { __walk_runtime_error(error); }
    return value;
}

static WALK_UNUSED FileReadResult __walk_file_try_read(WalkString path) {
    WalkString error = "";
    WalkString value = __walk_file_read_try_value(path, &error);
    if (error[0] != '\0') { return (FileReadResult){.ok = false, .value = "", .error = error}; }
    return (FileReadResult){.ok = true, .value = value, .error = ""};
}

static WALK_UNUSED WalkString __walk_file_write_try_error(WalkString path, WalkString text, const char *mode, const char *failure) {
    if (path == NULL || path[0] == '\0') { return "file path empty"; }
    if (text == NULL || !__walk_is_valid_utf8(text)) { return "file invalid utf-8"; }
    FILE *file = fopen(path, mode);
    if (file == NULL) { return failure; }
    size_t len = strlen(text);
    if (len > 0 && fwrite(text, 1, len, file) != len) {
        fclose(file);
        return failure;
    }
    if (fclose(file) != 0) { return failure; }
    return "";
}

static WALK_UNUSED void __walk_file_write(WalkString path, WalkString text) {
    WalkString error = __walk_file_write_try_error(path, text, "wb", "file write failed");
    if (error[0] != '\0') { __walk_runtime_error(error); }
}

static WALK_UNUSED FileActionResult __walk_file_try_write(WalkString path, WalkString text) {
    WalkString error = __walk_file_write_try_error(path, text, "wb", "file write failed");
    WalkBool ok = error[0] == '\0';
    return (FileActionResult){.ok = ok, .value = ok, .error = error};
}

static WALK_UNUSED void __walk_file_append(WalkString path, WalkString text) {
    WalkString error = __walk_file_write_try_error(path, text, "ab", "file append failed");
    if (error[0] != '\0') { __walk_runtime_error(error); }
}

static WALK_UNUSED FileActionResult __walk_file_try_append(WalkString path, WalkString text) {
    WalkString error = __walk_file_write_try_error(path, text, "ab", "file append failed");
    WalkBool ok = error[0] == '\0';
    return (FileActionResult){.ok = ok, .value = ok, .error = error};
}

static WALK_UNUSED WalkBool __walk_file_exists(WalkString path) {
    if (path == NULL || path[0] == '\0') { return false; }
#if defined(_WIN32)
    struct _stat info;
    return _stat(path, &info) == 0;
#else
    struct stat info;
    return stat(path, &info) == 0;
#endif
}

static WALK_UNUSED void __walk_array_string_push_owned(WalkString **items, WalkSize *len, WalkSize *cap, WalkString item) {
    if (*len >= *cap) {
        WalkSize next_cap = *cap == 0 ? 4 : *cap * 2;
        if (next_cap <= *cap || (size_t)next_cap > ((size_t)-1) / sizeof(WalkString)) { __walk_runtime_error("out of memory"); }
        WalkString *next_items = (WalkString *)realloc(*items, (size_t)next_cap * sizeof(WalkString));
        if (next_items == NULL) { __walk_runtime_error("out of memory"); }
        *items = next_items;
        *cap = next_cap;
    }
    (*items)[*len] = item;
    *len += 1;
}

static WALK_UNUSED int __walk_string_pointer_compare(const void *left, const void *right) {
    const WalkString *a = (const WalkString *)left;
    const WalkString *b = (const WalkString *)right;
    return strcmp(*a, *b);
}

static WALK_UNUSED WalkArrayString __walk_dir_list(WalkString path) {
    if (path == NULL || path[0] == '\0') { __walk_runtime_error("dir path empty"); }
    WalkString *items = NULL;
    WalkSize len = 0;
    WalkSize cap = 0;
#if defined(_WIN32)
    size_t path_len = strlen(path);
    WalkBool needs_sep = path_len > 0 && path[path_len - 1] != '/' && path[path_len - 1] != '\\';
    size_t pattern_len = path_len + (needs_sep ? 2 : 1) + 1;
    char *pattern = (char *)malloc(pattern_len);
    if (pattern == NULL) { __walk_runtime_error("out of memory"); }
    if (needs_sep) { snprintf(pattern, pattern_len, "%s\\*", path); } else { snprintf(pattern, pattern_len, "%s*", path); }
    WIN32_FIND_DATAA data;
    HANDLE handle = FindFirstFileA(pattern, &data);
    free(pattern);
    if (handle == INVALID_HANDLE_VALUE) { __walk_runtime_error("dir list failed"); }
    do {
        if (strcmp(data.cFileName, ".") != 0 && strcmp(data.cFileName, "..") != 0) { __walk_array_string_push_owned(&items, &len, &cap, __walk_copy_string(data.cFileName)); }
    } while (FindNextFileA(handle, &data) != 0);
    DWORD find_error = GetLastError();
    FindClose(handle);
    if (find_error != ERROR_NO_MORE_FILES) { __walk_runtime_error("dir list failed"); }
#else
    DIR *dir = opendir(path);
    if (dir == NULL) { __walk_runtime_error("dir list failed"); }
    for (;;) {
        errno = 0;
        struct dirent *entry = readdir(dir);
        if (entry == NULL) {
            if (errno != 0) { closedir(dir); __walk_runtime_error("dir list failed"); }
            break;
        }
        if (strcmp(entry->d_name, ".") != 0 && strcmp(entry->d_name, "..") != 0) { __walk_array_string_push_owned(&items, &len, &cap, __walk_copy_string(entry->d_name)); }
    }
    if (closedir(dir) != 0) { __walk_runtime_error("dir list failed"); }
#endif
    if (len > 1) { qsort(items, (size_t)len, sizeof(WalkString), __walk_string_pointer_compare); }
    return (WalkArrayString){items, len};
}

static WALK_UNUSED void __walk_dir_make(WalkString path) {
    if (path == NULL || path[0] == '\0') { __walk_runtime_error("dir path empty"); }
#if defined(_WIN32)
    if (_mkdir(path) != 0) { __walk_runtime_error("dir make failed"); }
#else
    if (mkdir(path, 0777) != 0) { __walk_runtime_error("dir make failed"); }
#endif
}

static WALK_UNUSED void __walk_dir_delete(WalkString path) {
    if (path == NULL || path[0] == '\0') { __walk_runtime_error("dir path empty"); }
#if defined(_WIN32)
    if (_rmdir(path) != 0) { __walk_runtime_error("dir delete failed"); }
#else
    if (rmdir(path) != 0) { __walk_runtime_error("dir delete failed"); }
#endif
}

static WALK_UNUSED WalkBool __walk_is_path_separator(char ch) {
    return ch == '/' || ch == '\\';
}

static WALK_UNUSED WalkString __walk_path_join(WalkString left, WalkString right) {
    if (left == NULL) { left = ""; }
    if (right == NULL) { right = ""; }
    size_t left_len = strlen(left);
    size_t right_len = strlen(right);
    if (left_len == 0) { return __walk_copy_string(right); }
    if (right_len == 0) { return __walk_copy_string(left); }
    WalkBool add_sep = !__walk_is_path_separator(left[left_len - 1]) && !__walk_is_path_separator(right[0]);
#if defined(_WIN32)
    const char sep = '\\';
#else
    const char sep = '/';
#endif
    size_t extra = add_sep ? 1 : 0;
    if (left_len > ((size_t)-1) - right_len - extra - 1) { __walk_runtime_error("out of memory"); }
    char *out = (char *)malloc(left_len + right_len + extra + 1);
    if (out == NULL) { __walk_runtime_error("out of memory"); }
    memcpy(out, left, left_len);
    size_t offset = left_len;
    if (add_sep) { out[offset++] = sep; }
    memcpy(out + offset, right, right_len + 1);
    return out;
}

static WALK_UNUSED WalkString __walk_path_base(WalkString path) {
    if (path == NULL) { return __walk_copy_string(""); }
    const char *base = path;
    for (const char *p = path; *p != '\0'; p++) { if (__walk_is_path_separator(*p)) { base = p + 1; } }
    return __walk_copy_string(base);
}

static WALK_UNUSED WalkString __walk_path_ext(WalkString path) {
    if (path == NULL) { return __walk_copy_string(""); }
    const char *dot = NULL;
    for (const char *p = path; *p != '\0'; p++) {
        if (__walk_is_path_separator(*p)) { dot = NULL; continue; }
        if (*p == '.') { dot = p; }
    }
    return __walk_copy_string(dot == NULL ? "" : dot);
}

static WALK_UNUSED WalkInt __walk_process_arg_count(void) {
    return __walk_host_argc > 0 ? (WalkInt)(__walk_host_argc - 1) : 0;
}

static WALK_UNUSED WalkArrayString __walk_process_args(void) {
    WalkInt count = __walk_process_arg_count();
    WalkString *items = (WalkString *)__walk_alloc_array(count, sizeof(WalkString));
    for (WalkInt i = 0; i < count; i++) { items[i] = __walk_host_argv[i + 1]; }
    return (WalkArrayString){items, count};
}

static WALK_UNUSED WalkString __walk_process_env(WalkString name) {
    if (name == NULL) { return NULL; }
    return getenv(name);
}

static WALK_UNUSED WalkString __walk_process_cwd(void) {
    size_t cap = 256;
    for (;;) {
        char *buffer = (char *)malloc(cap);
        if (buffer == NULL) { __walk_runtime_error("out of memory"); }
        errno = 0;
#if defined(_WIN32)
        if (cap > (size_t)INT_MAX) {
            free(buffer);
            __walk_runtime_error("cwd path too long");
        }
        if (_getcwd(buffer, (int)cap) != NULL) { return buffer; }
#else
        if (getcwd(buffer, cap) != NULL) { return buffer; }
#endif
        if (errno != ERANGE) {
            free(buffer);
            __walk_runtime_error("cwd failed");
        }
        free(buffer);
        if (cap > ((size_t)-1) / 2) { __walk_runtime_error("cwd path too long"); }
        cap *= 2;
    }
}

static WALK_UNUSED void __walk_process_chdir(WalkString path) {
    if (path == NULL || path[0] == '\0') { __walk_runtime_error("chdir path empty"); }
#if defined(_WIN32)
    if (_chdir(path) != 0) { __walk_runtime_error("chdir failed"); }
#else
    if (chdir(path) != 0) { __walk_runtime_error("chdir failed"); }
#endif
}

static WALK_UNUSED void __walk_process_exit(WalkInt code) {
    exit((int)code);
}

static WALK_UNUSED WalkBool __walk_parse_starts_with_space(WalkString text) {
    return text[0] == ' ' || text[0] == '\t' || text[0] == '\n' || text[0] == '\r' || text[0] == '\f' || text[0] == '\v';
}

static WALK_UNUSED ParseIntResult __walk_parse_int(WalkString text) {
    if (text == NULL || text[0] == '\0' || __walk_parse_starts_with_space(text)) {
        return (ParseIntResult){.ok = false, .value = 0, .error = "invalid int"};
    }
    errno = 0;
    char *end = NULL;
    long long value = strtoll(text, &end, 10);
    if (end == text || *end != '\0') {
        return (ParseIntResult){.ok = false, .value = 0, .error = "invalid int"};
    }
    if (errno == ERANGE) {
        return (ParseIntResult){.ok = false, .value = 0, .error = "int out of range"};
    }
    return (ParseIntResult){.ok = true, .value = (WalkInt)value, .error = ""};
}

static WALK_UNUSED ParseFloatResult __walk_parse_float(WalkString text) {
    if (text == NULL || text[0] == '\0' || __walk_parse_starts_with_space(text)) {
        return (ParseFloatResult){.ok = false, .value = 0, .error = "invalid float"};
    }
    errno = 0;
    char *end = NULL;
    double value = strtod(text, &end);
    if (end == text || *end != '\0' || !isfinite(value)) {
        return (ParseFloatResult){.ok = false, .value = 0, .error = "invalid float"};
    }
    if (errno == ERANGE) {
        return (ParseFloatResult){.ok = false, .value = 0, .error = "float out of range"};
    }
    return (ParseFloatResult){.ok = true, .value = (WalkFloat)value, .error = ""};
}

static WALK_UNUSED ParseBoolResult __walk_parse_bool(WalkString text) {
    if (text != NULL && strcmp(text, "true") == 0) {
        return (ParseBoolResult){.ok = true, .value = true, .error = ""};
    }
    if (text != NULL && strcmp(text, "false") == 0) {
        return (ParseBoolResult){.ok = true, .value = false, .error = ""};
    }
    return (ParseBoolResult){.ok = false, .value = false, .error = "invalid bool"};
}

WalkInt add(WalkInt a, WalkInt b);
WalkInt fact(WalkInt n);

WalkInt add(WalkInt a, WalkInt b) {
    /* source: functions.walk:2:5 */
    return (a + b);
}

WalkInt fact(WalkInt n) {
    /* source: functions.walk:5:5 */
    if ((n <= 1)) {
        /* source: functions.walk:6:9 */
        return 1;
    }
    /* source: functions.walk:7:5 */
    return (n * fact((n - 1)));
}

int main(int argc, char **argv) {
    __walk_host_argc = argc;
    __walk_host_argv = argv;
    /* source: functions.walk:9:1 */
    __walk_print_int((WalkInt)(add(2, 3)));
    /* source: functions.walk:10:1 */
    __walk_print_int((WalkInt)(fact(5)));
    return 0;
}
