/* Generated by WalkLang. C is the primary backend and is intended to stay inspectable. */

#include <math.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <time.h>

/* walk runtime: no user pointers; array storage is runtime-owned for the process lifetime. */
typedef long long WalkInt;
typedef double WalkFloat;
typedef bool WalkBool;
typedef const char *WalkString;
typedef long long WalkSize;

typedef struct { WalkInt *items; WalkSize len; } WalkArrayInt;
typedef struct { WalkFloat *items; WalkSize len; } WalkArrayFloat;
typedef struct { WalkBool *items; WalkSize len; } WalkArrayBool;
typedef struct { WalkString *items; WalkSize len; } WalkArrayString;

#if defined(__GNUC__) || defined(__clang__)
#define WALK_UNUSED __attribute__((unused))
#else
#define WALK_UNUSED
#endif

static WALK_UNUSED void *__walk_alloc_array(WalkSize len, size_t item_size) {
    if (len <= 0) { return NULL; }
    void *items = calloc((size_t)len, item_size);
    if (items == NULL) {
        fprintf(stderr, "walk runtime error: out of memory\n");
        exit(1);
    }
    return items;
}

static WALK_UNUSED void __walk_runtime_error(const char *message) {
    fprintf(stderr, "walk runtime error: %s\n", message);
    exit(1);
}

static WALK_UNUSED WalkInt __walk_random_int(WalkInt min, WalkInt max) {
    if (max < min) { return min; }
    return min + (rand() % (max - min + 1));
}

static WALK_UNUSED WalkSize __walk_random_index(WalkSize len) {
    if (len <= 0) { __walk_runtime_error("random.choice on empty array"); }
    return (WalkSize)(rand() % len);
}

static WALK_UNUSED WalkInt __walk_string_len(WalkString value) {
    return value == NULL ? 0 : (WalkInt)strlen(value);
}

static WALK_UNUSED WalkString __walk_string_at(WalkString value, WalkInt index) {
    WalkSize len = (WalkSize)__walk_string_len(value);
    if (index < 0 || index >= len) { __walk_runtime_error("string index out of range"); }
    char *out = (char *)malloc(2);
    if (out == NULL) { __walk_runtime_error("out of memory"); }
    out[0] = value[index];
    out[1] = '\0';
    return out;
}

static WALK_UNUSED WalkBool __walk_string_contains(WalkString text, WalkString item) {
    if (text == NULL) { text = ""; }
    if (item == NULL) { item = ""; }
    return strstr(text, item) != NULL;
}

static WALK_UNUSED WalkString __walk_string_concat(WalkString left, WalkString right) {
    if (left == NULL) { left = ""; }
    if (right == NULL) { right = ""; }
    size_t left_len = strlen(left);
    size_t right_len = strlen(right);
    if (left_len > ((size_t)-1) - right_len - 1) { __walk_runtime_error("out of memory"); }
    char *out = (char *)malloc(left_len + right_len + 1);
    if (out == NULL) { __walk_runtime_error("out of memory"); }
    memcpy(out, left, left_len);
    memcpy(out + left_len, right, right_len);
    out[left_len + right_len] = '\0';
    return out;
}

static WALK_UNUSED WalkArrayInt __walk_array_push_int(WalkArrayInt array, WalkInt item) {
    WalkInt *items = (WalkInt *)__walk_alloc_array(array.len + 1, sizeof(WalkInt));
    for (WalkSize i = 0; i < array.len; i++) { items[i] = array.items[i]; }
    items[array.len] = item;
    return (WalkArrayInt){items, array.len + 1};
}

static WALK_UNUSED WalkArrayFloat __walk_array_push_float(WalkArrayFloat array, WalkFloat item) {
    WalkFloat *items = (WalkFloat *)__walk_alloc_array(array.len + 1, sizeof(WalkFloat));
    for (WalkSize i = 0; i < array.len; i++) { items[i] = array.items[i]; }
    items[array.len] = item;
    return (WalkArrayFloat){items, array.len + 1};
}

static WALK_UNUSED WalkArrayBool __walk_array_push_bool(WalkArrayBool array, WalkBool item) {
    WalkBool *items = (WalkBool *)__walk_alloc_array(array.len + 1, sizeof(WalkBool));
    for (WalkSize i = 0; i < array.len; i++) { items[i] = array.items[i]; }
    items[array.len] = item;
    return (WalkArrayBool){items, array.len + 1};
}

static WALK_UNUSED WalkArrayString __walk_array_push_string(WalkArrayString array, WalkString item) {
    WalkString *items = (WalkString *)__walk_alloc_array(array.len + 1, sizeof(WalkString));
    for (WalkSize i = 0; i < array.len; i++) { items[i] = array.items[i]; }
    items[array.len] = item;
    return (WalkArrayString){items, array.len + 1};
}

static WALK_UNUSED WalkBool __walk_array_contains_int(WalkArrayInt array, WalkInt item) {
    for (WalkSize i = 0; i < array.len; i++) { if (array.items[i] == item) { return true; } }
    return false;
}

static WALK_UNUSED WalkBool __walk_array_contains_float(WalkArrayFloat array, WalkFloat item) {
    for (WalkSize i = 0; i < array.len; i++) { if (array.items[i] == item) { return true; } }
    return false;
}

static WALK_UNUSED WalkBool __walk_array_contains_bool(WalkArrayBool array, WalkBool item) {
    for (WalkSize i = 0; i < array.len; i++) { if (array.items[i] == item) { return true; } }
    return false;
}

static WALK_UNUSED WalkBool __walk_array_contains_string(WalkArrayString array, WalkString item) {
    for (WalkSize i = 0; i < array.len; i++) { if (strcmp(array.items[i], item) == 0) { return true; } }
    return false;
}

static WALK_UNUSED WalkInt __walk_array_choice_int(WalkArrayInt array) { return array.items[__walk_random_index(array.len)]; }
static WALK_UNUSED WalkFloat __walk_array_choice_float(WalkArrayFloat array) { return array.items[__walk_random_index(array.len)]; }
static WALK_UNUSED WalkBool __walk_array_choice_bool(WalkArrayBool array) { return array.items[__walk_random_index(array.len)]; }
static WALK_UNUSED WalkString __walk_array_choice_string(WalkArrayString array) { return array.items[__walk_random_index(array.len)]; }

static WALK_UNUSED WalkString __walk_input(WalkString prompt) {
    if (prompt != NULL) {
        fputs(prompt, stdout);
        fflush(stdout);
    }
    size_t cap = 64;
    size_t len = 0;
    char *buffer = (char *)malloc(cap);
    if (buffer == NULL) {
        fprintf(stderr, "walk runtime error: out of memory\n");
        exit(1);
    }
    for (;;) {
        int ch = fgetc(stdin);
        if (ch == EOF) {
            if (ferror(stdin)) {
                free(buffer);
                fprintf(stderr, "walk runtime error: stdin read failed\n");
                exit(1);
            }
            if (len == 0) {
                free(buffer);
                fprintf(stderr, "walk runtime error: input reached EOF\n");
                exit(1);
            }
            break;
        }
        if (ch == '\n') { break; }
        if (ch == '\r') {
            int next = fgetc(stdin);
            if (next == '\n') { break; }
            if (next == EOF && ferror(stdin)) {
                free(buffer);
                fprintf(stderr, "walk runtime error: stdin read failed\n");
                exit(1);
            }
            if (next != EOF) { ungetc(next, stdin); }
        }
        if (len + 1 >= cap) {
            if (cap > ((size_t)-1) / 2) {
                free(buffer);
                fprintf(stderr, "walk runtime error: out of memory\n");
                exit(1);
            }
            size_t next_cap = cap * 2;
            char *next_buffer = (char *)realloc(buffer, next_cap);
            if (next_buffer == NULL) {
                free(buffer);
                fprintf(stderr, "walk runtime error: out of memory\n");
                exit(1);
            }
            buffer = next_buffer;
            cap = next_cap;
        }
        buffer[len++] = (char)ch;
    }
    buffer[len] = '\0';
    return buffer;
}

static WALK_UNUSED void __walk_print_int(WalkInt value) { printf("%lld\n", (long long)value); }
static WALK_UNUSED void __walk_print_float(WalkFloat value) { printf("%g\n", (double)value); }
static WALK_UNUSED void __walk_print_bool(WalkBool value) { printf("%s\n", value ? "true" : "false"); }
static WALK_UNUSED void __walk_print_string(WalkString value) { printf("%s\n", value == NULL ? "null" : value); }

WalkInt add(WalkInt a, WalkInt b);
WalkInt fact(WalkInt n);

WalkInt add(WalkInt a, WalkInt b) {
    /* source: functions.walk:2:5 */
    return (a + b);
}

WalkInt fact(WalkInt n) {
    /* source: functions.walk:5:5 */
    if ((n <= 1)) {
        /* source: functions.walk:6:9 */
        return 1;
    }
    /* source: functions.walk:7:5 */
    return (n * fact((n - 1)));
}

int main(void) {
    /* source: functions.walk:9:1 */
    __walk_print_int((WalkInt)(add(2, 3)));
    /* source: functions.walk:10:1 */
    __walk_print_int((WalkInt)(fact(5)));
    return 0;
}
