/* Generated by WalkLang. C is the primary backend and is intended to stay inspectable. */

#include <errno.h>
#include <limits.h>
#include <math.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <time.h>

#if defined(_WIN32)
#include <direct.h>
#include <process.h>
#else
#include <sys/time.h>
#include <unistd.h>
#endif

/* walk runtime: no user pointers; array storage is runtime-owned for the process lifetime. */
typedef long long WalkInt;
typedef double WalkFloat;
typedef bool WalkBool;
typedef const char *WalkString;
typedef long long WalkSize;

typedef struct { WalkInt *items; WalkSize len; } WalkArrayInt;
typedef struct { WalkFloat *items; WalkSize len; } WalkArrayFloat;
typedef struct { WalkBool *items; WalkSize len; } WalkArrayBool;
typedef struct { WalkString *items; WalkSize len; } WalkArrayString;

static int __walk_host_argc = 0;
static char **__walk_host_argv = NULL;

#if defined(__GNUC__) || defined(__clang__)
#define WALK_UNUSED __attribute__((unused))
#else
#define WALK_UNUSED
#endif

static WALK_UNUSED void *__walk_alloc_array(WalkSize len, size_t item_size) {
    if (len <= 0) { return NULL; }
    void *items = calloc((size_t)len, item_size);
    if (items == NULL) {
        fprintf(stderr, "walk runtime error: out of memory\n");
        exit(1);
    }
    return items;
}

static WALK_UNUSED void __walk_runtime_error(const char *message) {
    fprintf(stderr, "walk runtime error: %s\n", message);
    exit(1);
}

static unsigned long long __walk_random_state = 0;

static WALK_UNUSED unsigned long long __walk_random_seed(void) {
    unsigned long long seed = (unsigned long long)time(NULL);
    seed ^= ((unsigned long long)clock() << 32);
    seed ^= (unsigned long long)(uintptr_t)&seed;
#if defined(_WIN32)
    seed ^= ((unsigned long long)_getpid() << 16);
#else
    struct timeval tv;
    if (gettimeofday(&tv, NULL) == 0) {
        seed ^= ((unsigned long long)tv.tv_sec << 32) ^ (unsigned long long)tv.tv_usec;
    }
    seed ^= ((unsigned long long)getpid() << 16);
#endif
    if (seed == 0) { seed = 0x9e3779b97f4a7c15ULL; }
    return seed;
}

static WALK_UNUSED unsigned long long __walk_random_next(void) {
    if (__walk_random_state == 0) { __walk_random_state = __walk_random_seed(); }
    unsigned long long x = __walk_random_state;
    x ^= x >> 12;
    x ^= x << 25;
    x ^= x >> 27;
    __walk_random_state = x;
    return x * 2685821657736338717ULL;
}

static WALK_UNUSED WalkInt __walk_random_int(WalkInt min, WalkInt max) {
    if (max < min) { return min; }
    return min + (WalkInt)(__walk_random_next() % (unsigned long long)(max - min + 1));
}

static WALK_UNUSED WalkSize __walk_random_index(WalkSize len) {
    if (len <= 0) { __walk_runtime_error("random.choice on empty array"); }
    return (WalkSize)(__walk_random_next() % (unsigned long long)len);
}

static WALK_UNUSED WalkInt __walk_string_len(WalkString value) {
    return value == NULL ? 0 : (WalkInt)strlen(value);
}

static WALK_UNUSED WalkString __walk_string_at(WalkString value, WalkInt index) {
    WalkSize len = (WalkSize)__walk_string_len(value);
    if (index < 0 || index >= len) { __walk_runtime_error("string index out of range"); }
    char *out = (char *)malloc(2);
    if (out == NULL) { __walk_runtime_error("out of memory"); }
    out[0] = value[index];
    out[1] = '\0';
    return out;
}

static WALK_UNUSED WalkBool __walk_string_contains(WalkString text, WalkString item) {
    if (text == NULL) { text = ""; }
    if (item == NULL) { item = ""; }
    return strstr(text, item) != NULL;
}

static WALK_UNUSED WalkString __walk_string_concat(WalkString left, WalkString right) {
    if (left == NULL) { left = ""; }
    if (right == NULL) { right = ""; }
    size_t left_len = strlen(left);
    size_t right_len = strlen(right);
    if (left_len > ((size_t)-1) - right_len - 1) { __walk_runtime_error("out of memory"); }
    char *out = (char *)malloc(left_len + right_len + 1);
    if (out == NULL) { __walk_runtime_error("out of memory"); }
    memcpy(out, left, left_len);
    memcpy(out + left_len, right, right_len);
    out[left_len + right_len] = '\0';
    return out;
}

static WALK_UNUSED WalkString __walk_format_int(WalkInt value) {
    char buffer[64];
    int len = snprintf(buffer, sizeof(buffer), "%lld", (long long)value);
    if (len < 0 || (size_t)len >= sizeof(buffer)) { __walk_runtime_error("format failed"); }
    char *out = (char *)malloc((size_t)len + 1);
    if (out == NULL) { __walk_runtime_error("out of memory"); }
    memcpy(out, buffer, (size_t)len + 1);
    return out;
}

static WALK_UNUSED WalkString __walk_format_float(WalkFloat value) {
    char buffer[64];
    int len = snprintf(buffer, sizeof(buffer), "%g", (double)value);
    if (len < 0 || (size_t)len >= sizeof(buffer)) { __walk_runtime_error("format failed"); }
    char *out = (char *)malloc((size_t)len + 1);
    if (out == NULL) { __walk_runtime_error("out of memory"); }
    memcpy(out, buffer, (size_t)len + 1);
    return out;
}

static WALK_UNUSED WalkString __walk_format_bool(WalkBool value) {
    return value ? "true" : "false";
}

static WALK_UNUSED WalkString __walk_format_string(WalkString value) {
    return value == NULL ? "null" : value;
}

static WALK_UNUSED WalkArrayInt __walk_array_push_int(WalkArrayInt array, WalkInt item) {
    WalkInt *items = (WalkInt *)__walk_alloc_array(array.len + 1, sizeof(WalkInt));
    for (WalkSize i = 0; i < array.len; i++) { items[i] = array.items[i]; }
    items[array.len] = item;
    return (WalkArrayInt){items, array.len + 1};
}

static WALK_UNUSED WalkArrayFloat __walk_array_push_float(WalkArrayFloat array, WalkFloat item) {
    WalkFloat *items = (WalkFloat *)__walk_alloc_array(array.len + 1, sizeof(WalkFloat));
    for (WalkSize i = 0; i < array.len; i++) { items[i] = array.items[i]; }
    items[array.len] = item;
    return (WalkArrayFloat){items, array.len + 1};
}

static WALK_UNUSED WalkArrayBool __walk_array_push_bool(WalkArrayBool array, WalkBool item) {
    WalkBool *items = (WalkBool *)__walk_alloc_array(array.len + 1, sizeof(WalkBool));
    for (WalkSize i = 0; i < array.len; i++) { items[i] = array.items[i]; }
    items[array.len] = item;
    return (WalkArrayBool){items, array.len + 1};
}

static WALK_UNUSED WalkArrayString __walk_array_push_string(WalkArrayString array, WalkString item) {
    WalkString *items = (WalkString *)__walk_alloc_array(array.len + 1, sizeof(WalkString));
    for (WalkSize i = 0; i < array.len; i++) { items[i] = array.items[i]; }
    items[array.len] = item;
    return (WalkArrayString){items, array.len + 1};
}

static WALK_UNUSED WalkBool __walk_array_contains_int(WalkArrayInt array, WalkInt item) {
    for (WalkSize i = 0; i < array.len; i++) { if (array.items[i] == item) { return true; } }
    return false;
}

static WALK_UNUSED WalkBool __walk_array_contains_float(WalkArrayFloat array, WalkFloat item) {
    for (WalkSize i = 0; i < array.len; i++) { if (array.items[i] == item) { return true; } }
    return false;
}

static WALK_UNUSED WalkBool __walk_array_contains_bool(WalkArrayBool array, WalkBool item) {
    for (WalkSize i = 0; i < array.len; i++) { if (array.items[i] == item) { return true; } }
    return false;
}

static WALK_UNUSED WalkBool __walk_array_contains_string(WalkArrayString array, WalkString item) {
    for (WalkSize i = 0; i < array.len; i++) { if (strcmp(array.items[i], item) == 0) { return true; } }
    return false;
}

static WALK_UNUSED WalkInt __walk_array_choice_int(WalkArrayInt array) { return array.items[__walk_random_index(array.len)]; }
static WALK_UNUSED WalkFloat __walk_array_choice_float(WalkArrayFloat array) { return array.items[__walk_random_index(array.len)]; }
static WALK_UNUSED WalkBool __walk_array_choice_bool(WalkArrayBool array) { return array.items[__walk_random_index(array.len)]; }
static WALK_UNUSED WalkString __walk_array_choice_string(WalkArrayString array) { return array.items[__walk_random_index(array.len)]; }

static WALK_UNUSED WalkString __walk_input(WalkString prompt) {
    if (prompt != NULL) {
        fputs(prompt, stdout);
        fflush(stdout);
    }
    size_t cap = 64;
    size_t len = 0;
    char *buffer = (char *)malloc(cap);
    if (buffer == NULL) {
        fprintf(stderr, "walk runtime error: out of memory\n");
        exit(1);
    }
    for (;;) {
        int ch = fgetc(stdin);
        if (ch == EOF) {
            if (ferror(stdin)) {
                free(buffer);
                fprintf(stderr, "walk runtime error: stdin read failed\n");
                exit(1);
            }
            if (len == 0) {
                free(buffer);
                fprintf(stderr, "walk runtime error: input reached EOF\n");
                exit(1);
            }
            break;
        }
        if (ch == '\n') { break; }
        if (ch == '\r') {
            int next = fgetc(stdin);
            if (next == '\n') { break; }
            if (next == EOF && ferror(stdin)) {
                free(buffer);
                fprintf(stderr, "walk runtime error: stdin read failed\n");
                exit(1);
            }
            if (next != EOF) { ungetc(next, stdin); }
        }
        if (len + 1 >= cap) {
            if (cap > ((size_t)-1) / 2) {
                free(buffer);
                fprintf(stderr, "walk runtime error: out of memory\n");
                exit(1);
            }
            size_t next_cap = cap * 2;
            char *next_buffer = (char *)realloc(buffer, next_cap);
            if (next_buffer == NULL) {
                free(buffer);
                fprintf(stderr, "walk runtime error: out of memory\n");
                exit(1);
            }
            buffer = next_buffer;
            cap = next_cap;
        }
        buffer[len++] = (char)ch;
    }
    buffer[len] = '\0';
    return buffer;
}

static WALK_UNUSED void __walk_print_int(WalkInt value) { printf("%lld\n", (long long)value); }
static WALK_UNUSED void __walk_print_float(WalkFloat value) { printf("%g\n", (double)value); }
static WALK_UNUSED void __walk_print_bool(WalkBool value) { printf("%s\n", value ? "true" : "false"); }
static WALK_UNUSED void __walk_print_string(WalkString value) { printf("%s\n", value == NULL ? "null" : value); }

static WALK_UNUSED void __walk_io_write(WalkString value) {
    fputs(value == NULL ? "null" : value, stdout);
    fflush(stdout);
}

static WALK_UNUSED void __walk_io_write_line(WalkString value) {
    fprintf(stdout, "%s\n", value == NULL ? "null" : value);
    fflush(stdout);
}

static WALK_UNUSED void __walk_io_error_line(WalkString value) {
    fprintf(stderr, "%s\n", value == NULL ? "null" : value);
    fflush(stderr);
}

static WALK_UNUSED WalkInt __walk_process_arg_count(void) {
    return __walk_host_argc > 0 ? (WalkInt)(__walk_host_argc - 1) : 0;
}

static WALK_UNUSED WalkArrayString __walk_process_args(void) {
    WalkInt count = __walk_process_arg_count();
    WalkString *items = (WalkString *)__walk_alloc_array(count, sizeof(WalkString));
    for (WalkInt i = 0; i < count; i++) { items[i] = __walk_host_argv[i + 1]; }
    return (WalkArrayString){items, count};
}

static WALK_UNUSED WalkString __walk_process_env(WalkString name) {
    if (name == NULL) { return NULL; }
    return getenv(name);
}

static WALK_UNUSED WalkString __walk_process_cwd(void) {
    size_t cap = 256;
    for (;;) {
        char *buffer = (char *)malloc(cap);
        if (buffer == NULL) { __walk_runtime_error("out of memory"); }
        errno = 0;
#if defined(_WIN32)
        if (cap > (size_t)INT_MAX) {
            free(buffer);
            __walk_runtime_error("cwd path too long");
        }
        if (_getcwd(buffer, (int)cap) != NULL) { return buffer; }
#else
        if (getcwd(buffer, cap) != NULL) { return buffer; }
#endif
        if (errno != ERANGE) {
            free(buffer);
            __walk_runtime_error("cwd failed");
        }
        free(buffer);
        if (cap > ((size_t)-1) / 2) { __walk_runtime_error("cwd path too long"); }
        cap *= 2;
    }
}

static WALK_UNUSED void __walk_process_exit(WalkInt code) {
    exit((int)code);
}

int main(int argc, char **argv) {
    __walk_host_argc = argc;
    __walk_host_argv = argv;
    /* source: hello.walk:1:1 */
    __walk_print_string((WalkString)("hello"));
    /* source: hello.walk:2:1 */
    __walk_print_int((WalkInt)((1 + 2)));
    /* source: hello.walk:3:1 */
    __walk_print_bool((WalkBool)(true));
    return 0;
}
