/* Generated by WalkLang. C is the primary backend and is intended to stay inspectable. */

#include <math.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <time.h>

/* walk runtime: no user pointers; array storage is runtime-owned for the process lifetime. */
typedef long long WalkInt;
typedef double WalkFloat;
typedef bool WalkBool;
typedef const char *WalkString;
typedef long long WalkSize;

typedef struct { WalkInt *items; WalkSize len; } WalkArrayInt;
typedef struct { WalkFloat *items; WalkSize len; } WalkArrayFloat;
typedef struct { WalkBool *items; WalkSize len; } WalkArrayBool;
typedef struct { WalkString *items; WalkSize len; } WalkArrayString;

#if defined(__GNUC__) || defined(__clang__)
#define WALK_UNUSED __attribute__((unused))
#else
#define WALK_UNUSED
#endif

static WALK_UNUSED void *__walk_alloc_array(WalkSize len, size_t item_size) {
    if (len <= 0) { return NULL; }
    void *items = calloc((size_t)len, item_size);
    if (items == NULL) {
        fprintf(stderr, "walk runtime error: out of memory\n");
        exit(1);
    }
    return items;
}

static WALK_UNUSED WalkInt __walk_random_int(WalkInt min, WalkInt max) {
    if (max < min) { return min; }
    return min + (rand() % (max - min + 1));
}

static WALK_UNUSED WalkInt __walk_string_len(WalkString value) {
    return value == NULL ? 0 : (WalkInt)strlen(value);
}

static WALK_UNUSED WalkString __walk_input(WalkString prompt) {
    if (prompt != NULL) {
        fputs(prompt, stdout);
        fflush(stdout);
    }
    size_t cap = 64;
    size_t len = 0;
    char *buffer = (char *)malloc(cap);
    if (buffer == NULL) {
        fprintf(stderr, "walk runtime error: out of memory\n");
        exit(1);
    }
    for (;;) {
        int ch = fgetc(stdin);
        if (ch == EOF) {
            if (ferror(stdin)) {
                free(buffer);
                fprintf(stderr, "walk runtime error: stdin read failed\n");
                exit(1);
            }
            if (len == 0) {
                free(buffer);
                fprintf(stderr, "walk runtime error: input reached EOF\n");
                exit(1);
            }
            break;
        }
        if (ch == '\n') { break; }
        if (ch == '\r') {
            int next = fgetc(stdin);
            if (next == '\n') { break; }
            if (next == EOF && ferror(stdin)) {
                free(buffer);
                fprintf(stderr, "walk runtime error: stdin read failed\n");
                exit(1);
            }
            if (next != EOF) { ungetc(next, stdin); }
        }
        if (len + 1 >= cap) {
            if (cap > ((size_t)-1) / 2) {
                free(buffer);
                fprintf(stderr, "walk runtime error: out of memory\n");
                exit(1);
            }
            size_t next_cap = cap * 2;
            char *next_buffer = (char *)realloc(buffer, next_cap);
            if (next_buffer == NULL) {
                free(buffer);
                fprintf(stderr, "walk runtime error: out of memory\n");
                exit(1);
            }
            buffer = next_buffer;
            cap = next_cap;
        }
        buffer[len++] = (char)ch;
    }
    buffer[len] = '\0';
    return buffer;
}

static WALK_UNUSED void __walk_print_int(WalkInt value) { printf("%lld\n", (long long)value); }
static WALK_UNUSED void __walk_print_float(WalkFloat value) { printf("%g\n", (double)value); }
static WALK_UNUSED void __walk_print_bool(WalkBool value) { printf("%s\n", value ? "true" : "false"); }
static WALK_UNUSED void __walk_print_string(WalkString value) { printf("%s\n", value == NULL ? "null" : value); }

int main(void) {
    /* source: hello.walk:1:1 */
    __walk_print_string((WalkString)("hello"));
    /* source: hello.walk:2:1 */
    __walk_print_int((WalkInt)((1 + 2)));
    /* source: hello.walk:3:1 */
    __walk_print_bool((WalkBool)(true));
    return 0;
}
